import type { CoachLocale } from "@/components/coach/types";

const copy = {
  en: {
    eyebrow: "ZidRun Coach",
    title: "Train with a clear next step",
    intro: "Set a goal, log each run, and get a conservative plan grounded in your recent training.",
    overview: "Overview",
    plan: "Plan",
    runs: "Runs",
    runOverviewTitle: "Your running week",
    runOverviewSub: "A clear view of your momentum",
    runOverviewLatest: "Latest run",
    runOverviewBrowse: "View history",
    runOverviewEmpty: "Your first run will appear here.",
    runOverviewStreak: "week streak",
    runOverviewRecords: "Personal bests",
    runOverviewLongest: "Longest",
    runOverviewBestPace: "Best pace",
    runOverviewTotalDistance: "Total distance",
    runOverviewHighlights: "Highlights",
    runOverviewHighlightCount: (count: number) => `${count} earned`,
    runCountSummary: (count: number, distance: number) => `${count} ${count === 1 ? "run" : "runs"} · ${distance.toFixed(1)} km`,
    coach: "Coach",
    setupTitle: "Create your running goal",
    setupText: "Your availability and recent volume define the safe plan boundaries.",
    saveGoal: "Create goal",
    editGoal: "Edit goal",
    editGoalTitle: "Update your goal",
    editGoalText: "Change any detail below. Your next generated plan will use the new answers.",
    saveChanges: "Save changes",
    goalType: "Goal",
    targetDate: "Target date",
    targetDateFuture: "Target date must be in the future.",
    customGoalRequired: "Please describe your custom goal.",
    trainingDaysInvalid: "Choose between 2 and 7 training days.",
    longRunDayInvalid: "Your long-run day must be one of your training days.",
    fieldInvalid: "Please check the highlighted field and try again.",
    targetDistance: "Target distance (km)",
    targetTime: "Target time (HH:MM:SS)",
    experience: "Experience",
    weeklyDistance: "Current weekly distance (km)",
    trainingDays: "Available training days",
    longRunDay: "Preferred long-run day",
    constraints: "Training constraints",
    injuryNotes: "Injury or health notes",
    responseLanguage: "Coach language",
    currentGoal: "Current goal",
    target: "Target",
    thisWeek: "This week",
    last28: "Last 28 days",
    avgPace: "Average pace",
    fatigue: "Peak fatigue",
    nextWorkout: "Next workout",
    noWorkout: "Generate a weekly plan to see your next workout.",
    recentCoach: "Latest coach review",
    noReview: "No coach review yet.",
    loadOlder: "Load older messages",
    loadingOlder: "Loading…",
    historyStart: "You've reached the start of your history.",
    humanNote: "From your coach",
    generatePlan: "Generate weekly plan",
    reviewPlan: "Review next week",
    generating: "Coach is preparing your plan...",
    acceptPlan: "Accept plan",
    activePlan: "Active plan",
    today: "Today",
    planEndedTitle: "This week isn't planned yet",
    planEndedText: "Your active plan's week has ended. Generate this week's plan to get today's run and your daily reminders.",
    workoutDone: "Done",
    workoutMissed: "Missed",
    planThisWeek: "Your plan this week",
    adherenceComplete: "done",
    adherencePlanned: "planned",
    viewPlan: "View plan",
    noActivePlanTitle: "No active plan",
    noActivePlanText: "Log runs freely, or generate a plan to track your week.",
    adherenceMissedRow: "missed in a row",
    cantToday: "I can't today",
    moveWorkout: "Move",
    skipTitle: "No worries — what came up?",
    skipEncourage: "Missing one session is fine. Telling me why helps me adjust the next one.",
    skipNoReason: "Just skip",
    skipReasonSchedule: "Schedule",
    skipReasonFatigue: "Too tired",
    skipReasonPain: "Pain / symptoms",
    skipReasonWeather: "Weather",
    skipReasonIllness: "Illness",
    skipReasonTravel: "Travel",
    skipReasonMotivation: "Not feeling it",
    skipReasonOther: "Other",
    moveTitle: "Move to which day?",
    actionCancel: "Cancel",
    savingAction: "Saving…",
    skippedReasonLabel: "Reason",
    completionPartial: "Partial",
    completionEasier: "Easier than planned",
    completionHarder: "Harder than planned",
    matchAutoLinked: "Counted as “{title}”.",
    matchNotThisWorkout: "Not this workout?",
    matchSuggestQuestion: "Was this your “{title}”?",
    matchConfirmYes: "Yes, that's it",
    matchFreeRun: "No, free run",
    missedAskReason: "You missed this one — what came up?",
    logThisRun: "Log this run",
    restDayTitle: "Rest day",
    restDayText: "Recovery is training too — take it easy today.",
    todayDoneTitle: "Today's session is done",
    todayDoneText: "Nice work. Recover well for the next one.",
    noSessionToday: "No session scheduled today.",
    trainingSoFar: "Your training so far",
    freeRunnerIntro: "A read on your actual training — no plan needed yet.",
    freeRunnerRunsLabel: "Last 4 weeks",
    freeRunnerRunsValue: "{count} runs",
    freeRunnerInvite: "Want a plan built around this?",
    buildMyPlan: "Build my plan",
    draftPlan: "Draft plan",
    logRun: "Log a run",
    durationMinutes: "Duration (minutes)",
    distance: "Distance (km)",
    startedAt: "Date and time",
    effort: "Effort",
    runFatigue: "Fatigue",
    pain: "Pain",
    elevation: "Elevation gain (m)",
    heartRate: "Average heart rate",
    symptoms: "Symptoms",
    notes: "Run notes",
    analyzeNow: "Get coach feedback after saving",
    saveRun: "Save run",
    savingRun: "Saving run...",
    runHistory: "Recent runs",
    searchRuns: "Search runs",
    filterAll: "All",
    filterGps: "GPS",
    filterManual: "Manual",
    filterThisMonth: "This month",
    noFilteredRuns: "No runs match these filters.",
    runSavedJustNow: "Saved just now",
    noRuns: "No runs logged yet.",
    sleep: "Sleep",
    sleepHeading: "Sleep log",
    sleepIntro: "Track your nights — good sleep is when training turns into fitness.",
    logSleep: "Log sleep",
    sleepModeHours: "Hours",
    sleepModeTimes: "Times",
    sleepModeText: "Describe",
    sleepHoursLabel: "Hours slept",
    sleepBedTime: "Bed time",
    sleepWakeTime: "Wake time",
    sleepTextLabel: "Describe your sleep (any language)",
    sleepTextPlaceholder: "e.g. slept about 7 hours, or 11pm to 6am",
    sleepNight: "Night",
    sleepNoteLabel: "Note (optional)",
    saveSleep: "Save sleep",
    savingSleep: "Saving…",
    sleepSaved: "Sleep saved.",
    sleepSaveFailed: "Unable to save sleep.",
    noSleep: "No sleep logged yet.",
    sleepAvgLabel: "7-night average",
    sleepAiBadge: "AI",
    hoursUnit: "h",
    subscribeTitle: "AI Coach subscription",
    subscribeIntro: "Subscribe to keep training with your personal AI coach.",
    statusTrial: "Free trial",
    statusTrialEndsOn: "ends {date}",
    statusTrialEnded: "Your free trial has ended.",
    statusSubscribed: "Subscribed",
    statusSubscribedUntil: "until {date}",
    statusBlocked: "Subscribe to unlock the AI coach.",
    trialBannerDaysLeft: "{days} days left in your free trial",
    trialBannerLastDay: "Last day of your free trial",
    trialBannerText: "Subscribe to keep your AI coach after the trial and stay on track.",
    trialBannerCta: "Subscribe",
    choosePlan: "Choose a plan",
    planMonthly: "Monthly",
    planThreeMonths: "3 months",
    planYearly: "Yearly",
    planMonthsSuffix: "mo",
    payHowTitle: "How to pay",
    payBaridi: "BaridiMob",
    payCcp: "CCP",
    payCcpKey: "Key",
    payNoDetails: "Payment details will be shared with you shortly.",
    methodQuestion: "How did you pay?",
    methodBaridi: "BaridiMob",
    methodCcp: "CCP",
    proofFieldLabel: "Payment screenshot",
    proofFieldHelp: "Upload a clear screenshot of your transfer. JPG/PNG, max 5 MB.",
    submitRequest: "Submit for review",
    submittingRequest: "Submitting…",
    requestUnderReview: "Your payment is under review. We'll activate your subscription shortly.",
    requestDeclined: "Your last request was declined. Please submit a new payment below.",
    subHistoryTitle: "Subscription history",
    subHistoryEmpty: "No subscriptions yet.",
    subStatusActive: "Active",
    subStatusExpired: "Expired",
    subStatusCancelled: "Cancelled",
    subStartsLabel: "Start",
    subEndsLabel: "End",
    amountLabel: "Amount",
    currencyDa: "DA",
    backToCoach: "Back to coach",
    manageSubscription: "Manage subscription",
    withdrawRequest: "Cancel request",
    cancelSubscription: "Cancel subscription",
    analyzeRun: "Analyze run",
    viewAnalysis: "Coach analysis",
    askTitle: "Ask your coach",
    askPlaceholder: "How should I approach my next run?",
    ask: "Ask coach",
    record: "Record a voice note",
    recordStop: "Stop recording",
    recording: "Recording… tap to stop.",
    transcribing: "Transcribing your note…",
    transcribeError: "Could not transcribe. Please type instead.",
    micDenied: "Microphone access was denied.",
    thinking: "Coach is reviewing your training...",
    professional: "Professional assessment recommended",
    retry: "Try again",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    stepWord: "Step",
    ofWord: "of",
    next: "Next",
    back: "Back",
    optional: "Optional",
    optionalDetails: "Optional details",
    stepGoalLabel: "Goal",
    stepBackgroundLabel: "Background",
    stepAvailabilityLabel: "Availability",
    stepHealthLabel: "Health",
    stepReviewLabel: "Review",
    goalStepTitle: "What are you training for?",
    backgroundStepTitle: "Your running background",
    backgroundStepText: "This helps the coach set a safe, realistic starting load.",
    availabilityStepTitle: "When can you train?",
    healthStepTitle: "Health & safety",
    healthStepText: "Share anything that should keep your plan safe. This is optional and used only to personalize your training.",
    reviewStepTitle: "Review & confirm",
    yearsRunning: "Years running regularly",
    peakWeeklyDistance: "Highest weekly distance ever (km)",
    longestRecentRun: "Longest recent run (km)",
    recentRaceResult: "Recent race or time trial result",
    recentRaceResultHint: "e.g. 10K in 52:00 last month",
    restingHeartRate: "Resting heart rate (bpm)",
    weight: "Body weight (kg)",
    weightHint: "Used to estimate calories burned.",
    height: "Height (cm)",
    heightHint: "Used with weight for body-composition context.",
    sex: "Sex",
    sexMale: "Male",
    sexFemale: "Female",
    birthDate: "Date of birth",
    dobDay: "Day",
    dobMonth: "Month",
    dobYear: "Year",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    hoursLabel: "Hours",
    minutesLabel: "Minutes",
    secondsLabel: "Seconds",
    recordRun: "Record a run",
    recordHint: "Live GPS tracking",
    recordingStatus: "Recording",
    pausedStatus: "Paused",
    holdToStart: "Hold to begin",
    holdingToStart: "Keep holding…",
    startRun: "Start run",
    pause: "Pause",
    resume: "Resume",
    finishRun: "Finish",
    discard: "Discard",
    statDistance: "Distance",
    statTime: "Time",
    statMovingTime: "Moving",
    statPace: "Pace",
    statCurrentPace: "Current pace",
    statAvgPace: "Avg pace",
    statElevation: "Elevation",
    statCalories: "Calories",
    gpsAcquiring: "Acquiring GPS signal…",
    gpsWarmup: "GPS is settling. The map appears after a stable fix so an old cached location is not shown.",
    gpsError: "Couldn't get your location. Enable location permission for ZidRun.",
    openSettings: "Open settings",
    runTooShort: "Run is too short to save (needs at least 100 m and 1 min).",
    savedOffline: "Saved on your phone — it will upload automatically when you're back online.",
    recorderCrashTitle: "Recorder hit a snag",
    recorderCrashText: "Something went wrong loading the run recorder. This is usually a stuck recording from before — clearing it should fix it.",
    recorderCrashReset: "Clear and reload",
    recoverTitle: "Resume your run?",
    recoverText: "We found an unfinished run on this phone. Continue where you left off, or discard it.",
    recoverResume: "Resume run",
    recoverDiscard: "Discard",
    statGps: "GPS",
    gpsWeak: "Weak",
    gpsFair: "Fair",
    gpsStrong: "Strong",
    bgTitle: "Keep recording with the screen off",
    bgText: "Allow ZidRun to ignore battery optimization so Android won't pause GPS while your screen is off.",
    bgEnable: "Allow background recording",
    bgEnabled: "Background recording is on.",
    bgLocationTitle: "Location is turned off",
    bgLocationText: "Allow location access so ZidRun can record your run, even with the screen off.",
    bgLocationCta: "Enable location",
    statCadence: "Cadence",
    nonFootWarnTitle: "This doesn't look like a run on foot",
    nonFootWarnCadence: "Your step rate is very low for this speed — it looks like this was recorded on wheels or a motor (car, bike, scooter, skateboard…), not on foot. You can still save it, but it will be excluded from your stats, records, and coach — you can delete it anytime.",
    nonFootWarnSpeed: "This moved faster than a person can run on foot — it looks like it was recorded on wheels or a motor (car, bike, scooter, skateboard…). You can still save it, but it will be excluded from your stats, records, and coach — you can delete it anytime.",
    nonFootBadge: "Likely not on foot",
    excludedFromStatsBadge: "Excluded from stats",
    excludedFromStatsHint: "This activity doesn't look like it was on foot, so it's excluded from your stats, records, and coach. You can delete it anytime.",
    splitsLabel: "Splits (per km)",
    profileElevation: "Elevation",
    profilePace: "Pace",
    splitFastest: "Fastest",
    splitSlowest: "Slowest",
    gpxExport: "GPX",
    gpxPreparing: "Preparing GPX…",
    gpxSaveDialog: "Save or share GPX",
    gpxChooseDestination: "GPX is ready — choose an app or folder to save it.",
    gpxDownloadStarted: "GPX download started.",
    gpxExportFailed: "GPX wasn't exported: {reason}",
    gpxUnknownError: "Unknown error. Please try again.",
    gpxNativeUnsupported: "GPX export needs a newer version of the app. Please update ZidRun and try again.",
    pendingUploads: "{n} run waiting to upload",
    retryUpload: "Retry upload",
    shareRun: "Share this run publicly",
    shareHint: "Public runs appear on the ZidRun leaderboards for your wilaya.",
    publicLabel: "Public",
    privateLabel: "Private",
    injuryHistory: "Past injury history",
    injuryHistoryHint: "Previous injuries, even if recovered.",
    currentInjury: "Current injuries or limitations",
    chronicConditions: "Ongoing health conditions",
    chronicHint: "Select any that apply so the coach keeps your plan safe.",
    healthNotes: "Medication or other health notes",
    consentLabel: "I understand ZidRun Coach gives training guidance, not medical advice, and I agree to share this information to personalize my plan.",
    consentRequired: "Please confirm to continue.",
    trialBadge: "Free trial",
    trialEndsIn: "Trial ends {date}",
    subscribedUntil: "Subscribed until {date}",
    dailyUsageLabel: "Today {used}/{limit}",
    subscriptionRequiredTitle: "Your free trial has ended",
    subscriptionRequiredText: "Subscribe for 790 DA/month, 1,990 DA for 3 months, or 4,900 DA/year to keep using the AI coach. Contact ZidRun to activate your subscription.",
    requestFailed: "Coach request failed.",
    goalCreateFailed: "Unable to create goal.",
    runSaved: "Run saved.",
    runPendingTitle: "Run not saved yet",
    runPendingText: "If you leave this screen, it stays safely on this phone until you choose Save or Discard. It will not be uploaded or deleted automatically.",
    runSaveFailed: "Unable to save run.",
    runUpdateFailed: "Unable to update run.",
    runSavedFeedbackFailed: "Run saved, but coach feedback failed: {error}",
    minTrainingDays: "Choose at least two training days.",
    formDisclaimer: "ZidRun Coach provides training guidance, not medical diagnosis.",
    highPainWarning: "High pain will pause automated training advice and recommend professional assessment.",
    planSafetyNotice: "Workout dates, types and distance ceilings are enforced by ZidRun safety rules.",
    gpsRunLabel: "GPS run",
    manualRunLabel: "Manual run",
    details: "Details",
    runDetailsStats: "Run summary",
    runDetailsInsightTitle: "Performance read",
    runDetailsInsightSteady: (pace: string) => `A controlled effort at ${pace}/km. Your pacing looks consistent — a strong base for the next session.`,
    runDetailsInsightFastFinish: (pace: string) => `You finished faster at ${pace}/km. That lift at the end is a good sign — keep it smooth, not forced.`,
    runDetailsInsightVariable: "Your pace moved around today. Use the easier sections as recovery and keep the next run relaxed.",
    runDetailsRecommendationTitle: "Next step",
    runDetailsRecommendationEasy: "Keep the next 24 hours easy: hydrate, eat normally, and choose gentle movement if your legs feel heavy.",
    runDetailsRecommendationRest: "Make recovery the next session. A rest day or easy walk will help this work turn into fitness.",
    runDetailsHighlights: "Highlights",
    runDetailsRoute: "Route",
    runDetailsNoRoute: "No GPS route was recorded for this run.",
    runDetailsEffort: "Effort",
    runDetailsHeartRate: "Avg heart rate",
    runDetailsCadence: "Cadence",
    runDetailsElevation: "Elevation",
    runDetailsCalories: "Calories",
    visibility: "Visibility",
    runTitle: "Title",
    runTitlePlaceholder: "e.g. Morning run, hill repeats…",
    description: "Description",
    descriptionPlaceholder: "How did the run feel? Anything worth remembering…",
    deleteRun: "Delete run",
    deleteRunTitle: "Delete this run?",
    deleteRunText: "This permanently removes the run and all its data. This can't be undone.",
    deletePhotoTitle: "Remove this photo?",
    deletePhotoText: "The photo will be removed from this run.",
    confirmDelete: "Delete",
    cancel: "Cancel",
    photos: "Photos",
    addPhoto: "Add photo",
    photoHelp: "JPG, PNG, WebP, or GIF. Up to 6, max 5 MB each.",
    photoUploading: "Uploading…",
    removePhoto: "Remove photo",
    viewPhoto: "View photo",
    photoUploadFailed: "Could not upload the photo. Try a smaller image.",
    saving: "Saving…",
    safetyTitle: "Safety boundary",
    safetyText: "ZidRun Coach can explain training patterns and propose conservative sessions. It does not diagnose injuries or replace professional care.",
    storedContext: "Stored context",
    storedItems: ["Goal and availability", "Recent runs and aggregate trends", "Current plan and safety signals"],
    requiredField: "Please complete: {field}",
    invalidField: "Please enter a valid {field}.",
    challengeTitle: "This week's challenge",
    challengeRuns: "Runs",
    challengeDistance: "Distance",
    streakLabel: "Week streak",
    streakNone: "Run this week to start a streak.",
    streakActive: "Keep it going — don't break the chain!",
    tipTitle: "Coach tip",
    newTip: "Another tip",
    suggestionsTitle: "Not sure what to ask? Try one of these",
    tips: [
      "Warm up with 5 minutes of easy jogging and leg swings before every run to prevent injury.",
      "Follow the 10% rule: don't increase your weekly distance by more than 10% to avoid overuse injuries.",
      "Cool down and stretch your calves, hamstrings, and quads after each run to aid recovery.",
      "Replace running shoes every 600–800 km — worn soles are a common cause of knee and shin pain.",
      "Hydrate before, during, and after long runs, and run in breathable, moisture-wicking clothing.",
      "Easy runs should feel conversational — if you can't talk in full sentences, slow down.",
      "Prioritise sleep: most of your fitness gains happen during recovery, not the run itself."
    ],
    suggestedQuestions: [
      "How can I avoid injury as I increase my distance?",
      "What should I eat before and after a long run?",
      "My knee hurts after running — what should I do?",
      "How do I improve my pace safely?",
      "What's a good warm-up and stretching routine?",
      "How many rest days do I need each week?"
    ],
    pushPromptTitle: "Turn on run reminders",
    pushPromptText: "Get a friendly push and email when you haven't run in a while, so you stay consistent.",
    pushEnable: "Enable reminders",
    pushDenied: "Notifications are blocked. Enable them in your browser settings.",
    pushFailed: "Couldn't enable notifications. Please try again.",
    dismiss: "Dismiss",
    memory: {
      nav: "Memory",
      title: "What your coach remembers",
      intro: "Durable facts your coach keeps between conversations, so it doesn't ask twice. You're in control — remove anything wrong or out of date.",
      healthNote: "Your coach never stores health, injury, or medical details here.",
      back: "Back to coach",
      loadFailed: "Couldn't load your coach's memory. Please try again.",
      actionFailed: "That didn't work. Please try again.",
      countLabel: "{n} remembered",
      emptyTitle: "Nothing remembered yet",
      emptyText: "As you talk with your coach, it remembers lasting things — when you like to run, the terrain you have, a constraint to plan around. They'll appear here for you to review or remove anytime.",
      ageToday: "Learned today",
      ageDaysAgo: "Learned {n} days ago",
      confirm: "Still true",
      confirming: "Saving…",
      forget: "Forget",
      forgetting: "Removing…",
      export: "Export",
      exporting: "Preparing…",
      deleteAll: "Delete all",
      deleteTitle: "Delete everything your coach remembers?",
      deleteText: "This clears every remembered fact for good. Your runs, plans and goals aren't affected — only what the coach learned about your preferences.",
      deleteConfirm: "Delete everything",
      deleting: "Deleting…",
      deleted: "Your coach's memory was cleared.",
      cancel: "Cancel",
      source: {
        stated: "You told your coach",
        inferred: "Your coach noticed",
        derived: "From your training",
        humanCoach: "From your coach"
      },
      kind: {
        preference: "Preference",
        coachingTone: "Coaching style",
        schedule: "Schedule",
        terrain: "Terrain",
        constraint: "Constraint",
        commitment: "Commitment",
        strategyWorked: "What works for you",
        strategyFailed: "What hasn't worked",
        rejectedSuggestion: "Advice you declined",
        coachNote: "Coach note"
      }
    }
  },
  fr: {
    eyebrow: "Coach ZidRun",
    title: "Entraînez-vous avec une prochaine étape claire",
    intro: "Définissez un objectif, enregistrez chaque sortie et recevez un plan prudent basé sur votre entraînement récent.",
    overview: "Aperçu",
    plan: "Plan",
    runs: "Sorties",
    runOverviewTitle: "Votre semaine de course",
    runOverviewSub: "Une vue claire de votre élan",
    runOverviewLatest: "Dernière sortie",
    runOverviewBrowse: "Voir l'historique",
    runOverviewEmpty: "Votre première sortie apparaîtra ici.",
    runOverviewStreak: "semaines de série",
    runOverviewRecords: "Records personnels",
    runOverviewLongest: "Plus longue",
    runOverviewBestPace: "Meilleure allure",
    runOverviewTotalDistance: "Distance totale",
    runOverviewHighlights: "Points forts",
    runOverviewHighlightCount: (count: number) => `${count} obtenus`,
    runCountSummary: (count: number, distance: number) => `${count} ${count === 1 ? "sortie" : "sorties"} · ${distance.toFixed(1)} km`,
    coach: "Coach",
    setupTitle: "Créez votre objectif de course",
    setupText: "Vos disponibilités et votre volume récent définissent les limites du plan.",
    saveGoal: "Créer l'objectif",
    editGoal: "Modifier l'objectif",
    editGoalTitle: "Modifier votre objectif",
    editGoalText: "Modifiez les détails de votre choix ci-dessous. Votre prochain plan tiendra compte de vos nouvelles réponses.",
    saveChanges: "Enregistrer",
    goalType: "Objectif",
    targetDate: "Date cible",
    targetDateFuture: "La date cible doit être dans le futur.",
    customGoalRequired: "Veuillez décrire votre objectif personnalisé.",
    trainingDaysInvalid: "Choisissez entre 2 et 7 jours d'entraînement.",
    longRunDayInvalid: "Votre jour de sortie longue doit être un de vos jours d'entraînement.",
    fieldInvalid: "Veuillez vérifier le champ indiqué et réessayer.",
    targetDistance: "Distance cible (km)",
    targetTime: "Temps cible (HH:MM:SS)",
    experience: "Expérience",
    weeklyDistance: "Distance hebdomadaire actuelle (km)",
    trainingDays: "Jours d'entraînement disponibles",
    longRunDay: "Jour préféré pour la sortie longue",
    constraints: "Contraintes d'entraînement",
    injuryNotes: "Blessures ou notes de santé",
    responseLanguage: "Langue du coach",
    currentGoal: "Objectif actuel",
    target: "Cible",
    thisWeek: "Cette semaine",
    last28: "28 derniers jours",
    avgPace: "Allure moyenne",
    fatigue: "Fatigue maximale",
    nextWorkout: "Prochaine séance",
    noWorkout: "Générez un plan hebdomadaire pour voir la prochaine séance.",
    recentCoach: "Dernier bilan du coach",
    noReview: "Aucun bilan du coach pour le moment.",
    loadOlder: "Charger les messages plus anciens",
    loadingOlder: "Chargement…",
    historyStart: "Vous avez atteint le début de votre historique.",
    humanNote: "De votre coach",
    generatePlan: "Générer le plan hebdomadaire",
    reviewPlan: "Préparer la semaine suivante",
    generating: "Le coach prépare votre plan...",
    acceptPlan: "Accepter le plan",
    activePlan: "Plan actif",
    today: "Aujourd'hui",
    planEndedTitle: "Cette semaine n'est pas encore planifiée",
    planEndedText: "La semaine de votre plan actif est terminée. Générez le plan de cette semaine pour obtenir la séance du jour et vos rappels quotidiens.",
    workoutDone: "Fait",
    workoutMissed: "Manquée",
    planThisWeek: "Votre plan cette semaine",
    adherenceComplete: "faites",
    adherencePlanned: "prévu",
    viewPlan: "Voir le plan",
    noActivePlanTitle: "Aucun plan actif",
    noActivePlanText: "Enregistrez vos sorties librement, ou générez un plan pour suivre votre semaine.",
    adherenceMissedRow: "manquées d'affilée",
    cantToday: "Pas aujourd'hui",
    moveWorkout: "Déplacer",
    skipTitle: "Pas de souci — qu'est-ce qui s'est passé ?",
    skipEncourage: "Manquer une séance n'est pas grave. M'en dire la raison m'aide à ajuster la suite.",
    skipNoReason: "Passer",
    skipReasonSchedule: "Emploi du temps",
    skipReasonFatigue: "Trop fatigué",
    skipReasonPain: "Douleur / symptômes",
    skipReasonWeather: "Météo",
    skipReasonIllness: "Maladie",
    skipReasonTravel: "Voyage",
    skipReasonMotivation: "Pas motivé",
    skipReasonOther: "Autre",
    moveTitle: "Déplacer à quel jour ?",
    actionCancel: "Annuler",
    savingAction: "Enregistrement…",
    skippedReasonLabel: "Raison",
    completionPartial: "Partielle",
    completionEasier: "Plus facile que prévu",
    completionHarder: "Plus dur que prévu",
    matchAutoLinked: "Comptée comme « {title} ».",
    matchNotThisWorkout: "Pas cette séance ?",
    matchSuggestQuestion: "Était-ce votre « {title} » ?",
    matchConfirmYes: "Oui, c'est ça",
    matchFreeRun: "Non, sortie libre",
    missedAskReason: "Vous avez manqué celle-ci — qu'est-ce qui s'est passé ?",
    logThisRun: "Enregistrer cette sortie",
    restDayTitle: "Jour de repos",
    restDayText: "La récupération fait partie de l'entraînement — allez-y doucement aujourd'hui.",
    todayDoneTitle: "La séance du jour est faite",
    todayDoneText: "Bravo. Récupérez bien pour la prochaine.",
    noSessionToday: "Aucune séance prévue aujourd'hui.",
    trainingSoFar: "Votre entraînement jusqu'ici",
    freeRunnerIntro: "Un aperçu de votre entraînement réel — sans plan pour l'instant.",
    freeRunnerRunsLabel: "4 dernières semaines",
    freeRunnerRunsValue: "{count} sorties",
    freeRunnerInvite: "Envie d'un plan bâti là-dessus ?",
    buildMyPlan: "Créer mon plan",
    draftPlan: "Plan proposé",
    logRun: "Enregistrer une sortie",
    durationMinutes: "Durée (minutes)",
    distance: "Distance (km)",
    startedAt: "Date et heure",
    effort: "Effort",
    runFatigue: "Fatigue",
    pain: "Douleur",
    elevation: "Dénivelé positif (m)",
    heartRate: "Fréquence cardiaque moyenne",
    symptoms: "Symptômes",
    notes: "Notes de sortie",
    analyzeNow: "Recevoir un retour du coach après l'enregistrement",
    saveRun: "Enregistrer",
    savingRun: "Enregistrement...",
    runHistory: "Sorties récentes",
    searchRuns: "Rechercher une sortie",
    filterAll: "Toutes",
    filterGps: "GPS",
    filterManual: "Manuelle",
    filterThisMonth: "Ce mois-ci",
    noFilteredRuns: "Aucune sortie ne correspond à ces filtres.",
    runSavedJustNow: "Enregistrée à l'instant",
    noRuns: "Aucune sortie enregistrée.",
    sleep: "Sommeil",
    sleepHeading: "Journal de sommeil",
    sleepIntro: "Suivez vos nuits — c'est pendant votre sommeil que l'entraînement se transforme en progrès.",
    logSleep: "Ajouter une nuit",
    sleepModeHours: "Heures",
    sleepModeTimes: "Horaires",
    sleepModeText: "Décrire",
    sleepHoursLabel: "Heures dormies",
    sleepBedTime: "Coucher",
    sleepWakeTime: "Réveil",
    sleepTextLabel: "Décrivez votre sommeil (toute langue)",
    sleepTextPlaceholder: "ex. dormi environ 7 heures, ou 23h à 6h",
    sleepNight: "Nuit",
    sleepNoteLabel: "Note (facultatif)",
    saveSleep: "Enregistrer",
    savingSleep: "Enregistrement…",
    sleepSaved: "Sommeil enregistré.",
    sleepSaveFailed: "Impossible d'enregistrer le sommeil.",
    noSleep: "Aucun sommeil enregistré.",
    sleepAvgLabel: "Moyenne 7 nuits",
    sleepAiBadge: "IA",
    hoursUnit: "h",
    subscribeTitle: "Abonnement Coach IA",
    subscribeIntro: "Abonnez-vous pour continuer avec votre coach IA personnel.",
    statusTrial: "Essai gratuit",
    statusTrialEndsOn: "se termine le {date}",
    statusTrialEnded: "Votre essai gratuit est terminé.",
    statusSubscribed: "Abonné",
    statusSubscribedUntil: "jusqu'au {date}",
    statusBlocked: "Abonnez-vous pour débloquer le coach IA.",
    trialBannerDaysLeft: "Il vous reste {days} jours d'essai gratuit",
    trialBannerLastDay: "Dernier jour de votre essai gratuit",
    trialBannerText: "Abonnez-vous pour conserver votre coach IA après l'essai et rester sur la bonne voie.",
    trialBannerCta: "S'abonner",
    choosePlan: "Choisir une formule",
    planMonthly: "Mensuel",
    planThreeMonths: "3 mois",
    planYearly: "Annuel",
    planMonthsSuffix: "mois",
    payHowTitle: "Comment payer",
    payBaridi: "BaridiMob",
    payCcp: "CCP",
    payCcpKey: "Clé",
    payNoDetails: "Les détails de paiement vous seront communiqués prochainement.",
    methodQuestion: "Comment avez-vous payé ?",
    methodBaridi: "BaridiMob",
    methodCcp: "CCP",
    proofFieldLabel: "Capture du paiement",
    proofFieldHelp: "Téléversez une capture claire de votre virement. JPG/PNG, max 5 Mo.",
    submitRequest: "Envoyer pour validation",
    submittingRequest: "Envoi…",
    requestUnderReview: "Votre paiement est en cours de vérification. Nous activerons votre abonnement bientôt.",
    requestDeclined: "Votre dernière demande a été refusée. Veuillez soumettre un nouveau paiement ci-dessous.",
    subHistoryTitle: "Historique des abonnements",
    subHistoryEmpty: "Aucun abonnement pour l'instant.",
    subStatusActive: "Actif",
    subStatusExpired: "Expiré",
    subStatusCancelled: "Annulé",
    subStartsLabel: "Début",
    subEndsLabel: "Fin",
    amountLabel: "Montant",
    currencyDa: "DA",
    backToCoach: "Retour au coach",
    manageSubscription: "Gérer l'abonnement",
    withdrawRequest: "Annuler la demande",
    cancelSubscription: "Annuler l'abonnement",
    analyzeRun: "Analyser",
    viewAnalysis: "Analyse du coach",
    askTitle: "Demandez à votre coach",
    askPlaceholder: "Comment aborder ma prochaine sortie ?",
    ask: "Demander",
    record: "Enregistrer une note vocale",
    recordStop: "Arrêter l’enregistrement",
    recording: "Enregistrement… appuyez pour arrêter.",
    transcribing: "Transcription de votre note…",
    transcribeError: "Transcription impossible. Saisissez le texte.",
    micDenied: "L’accès au microphone a été refusé.",
    thinking: "Le coach analyse votre entraînement...",
    professional: "Évaluation professionnelle recommandée",
    retry: "Réessayer",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    days: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
    stepWord: "Étape",
    ofWord: "sur",
    next: "Suivant",
    back: "Retour",
    optional: "Facultatif",
    optionalDetails: "Détails facultatifs",
    stepGoalLabel: "Objectif",
    stepBackgroundLabel: "Parcours",
    stepAvailabilityLabel: "Disponibilité",
    stepHealthLabel: "Santé",
    stepReviewLabel: "Vérifier",
    goalStepTitle: "Pour quoi vous entraînez-vous ?",
    backgroundStepTitle: "Votre parcours de coureur",
    backgroundStepText: "Cela aide le coach à définir une charge de départ sûre et réaliste.",
    availabilityStepTitle: "Quand pouvez-vous vous entraîner ?",
    healthStepTitle: "Santé et sécurité",
    healthStepText: "Indiquez ce qui peut aider à sécuriser votre plan. Ces informations sont facultatives et servent uniquement à personnaliser votre entraînement.",
    reviewStepTitle: "Vérifier et confirmer",
    yearsRunning: "Années de course régulière",
    peakWeeklyDistance: "Distance hebdomadaire maximale atteinte (km)",
    longestRecentRun: "Sortie récente la plus longue (km)",
    recentRaceResult: "Résultat récent de course ou test",
    recentRaceResultHint: "ex. 10 km en 52:00 le mois dernier",
    restingHeartRate: "Fréquence cardiaque au repos (bpm)",
    weight: "Poids (kg)",
    weightHint: "Sert à estimer les calories brûlées.",
    height: "Taille (cm)",
    heightHint: "Utilisée avec le poids pour le contexte morphologique.",
    sex: "Sexe",
    sexMale: "Homme",
    sexFemale: "Femme",
    birthDate: "Date de naissance",
    dobDay: "Jour",
    dobMonth: "Mois",
    dobYear: "Année",
    months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
    hoursLabel: "Heures",
    minutesLabel: "Minutes",
    secondsLabel: "Secondes",
    recordRun: "Enregistrer une sortie",
    recordHint: "Suivi GPS en direct",
    recordingStatus: "Enregistrement",
    pausedStatus: "En pause",
    holdToStart: "Maintenir pour démarrer",
    holdingToStart: "Maintenez encore…",
    startRun: "Démarrer",
    pause: "Pause",
    resume: "Reprendre",
    finishRun: "Terminer",
    discard: "Annuler",
    statDistance: "Distance",
    statTime: "Temps",
    statMovingTime: "En mouvement",
    statPace: "Allure",
    statCurrentPace: "Allure actuelle",
    statAvgPace: "Allure moy.",
    statElevation: "Dénivelé",
    statCalories: "Calories",
    gpsAcquiring: "Acquisition du signal GPS…",
    gpsWarmup: "Le GPS se stabilise. La carte s'affiche après un point fiable pour éviter d'afficher une ancienne position.",
    gpsError: "Localisation impossible. Activez la permission de localisation pour ZidRun.",
    openSettings: "Ouvrir les réglages",
    runTooShort: "Sortie trop courte pour être enregistrée (au moins 100 m et 1 min).",
    savedOffline: "Enregistré sur votre téléphone — l'envoi se fera automatiquement une fois en ligne.",
    recorderCrashTitle: "Le recorder a rencontré un problème",
    recorderCrashText: "Le chargement de l'enregistreur de course a échoué. C'est généralement un enregistrement bloqué — l'effacer devrait résoudre le problème.",
    recorderCrashReset: "Effacer et recharger",
    recoverTitle: "Reprendre votre sortie ?",
    recoverText: "Une sortie non terminée a été trouvée sur ce téléphone. Reprenez là où vous en étiez, ou supprimez-la.",
    recoverResume: "Reprendre",
    recoverDiscard: "Supprimer",
    statGps: "GPS",
    gpsWeak: "Faible",
    gpsFair: "Moyen",
    gpsStrong: "Bon",
    bgTitle: "Continuer l'enregistrement écran éteint",
    bgText: "Autorisez ZidRun à ignorer l'optimisation de batterie pour qu'Android ne suspende pas le GPS quand l'écran est éteint.",
    bgEnable: "Autoriser l'enregistrement en arrière-plan",
    bgEnabled: "Enregistrement en arrière-plan activé.",
    bgLocationTitle: "La localisation est désactivée",
    bgLocationText: "Autorisez l'accès à la localisation pour que ZidRun enregistre votre sortie, même écran éteint.",
    bgLocationCta: "Activer la localisation",
    statCadence: "Cadence",
    nonFootWarnTitle: "Cela ne ressemble pas à une course à pied",
    nonFootWarnCadence: "Votre cadence est très faible pour cette vitesse — cela semble avoir été enregistré sur roues ou avec un moteur (voiture, vélo, trottinette, skateboard…), pas à pied. Vous pouvez quand même l'enregistrer, mais elle sera exclue de vos statistiques, records et du coach — vous pouvez la supprimer à tout moment.",
    nonFootWarnSpeed: "Vous alliez plus vite qu'une personne ne peut courir à pied — cela semble avoir été enregistré sur roues ou avec un moteur (voiture, vélo, trottinette, skateboard…). Vous pouvez quand même l'enregistrer, mais elle sera exclue de vos statistiques, records et du coach — vous pouvez la supprimer à tout moment.",
    nonFootBadge: "Probablement pas à pied",
    excludedFromStatsBadge: "Exclue des statistiques",
    excludedFromStatsHint: "Cette activité ne semble pas avoir été faite à pied ; elle est donc exclue de vos statistiques, records et du coach. Vous pouvez la supprimer à tout moment.",
    splitsLabel: "Temps intermédiaires (par km)",
    profileElevation: "Altitude",
    profilePace: "Allure",
    splitFastest: "Le plus rapide",
    splitSlowest: "Le plus lent",
    gpxExport: "GPX",
    gpxPreparing: "Préparation du GPX…",
    gpxSaveDialog: "Enregistrer ou partager le GPX",
    gpxChooseDestination: "Le GPX est prêt — choisissez une application ou un dossier pour l'enregistrer.",
    gpxDownloadStarted: "Le téléchargement du GPX a commencé.",
    gpxExportFailed: "Le GPX n'a pas été exporté : {reason}",
    gpxUnknownError: "Erreur inconnue. Veuillez réessayer.",
    gpxNativeUnsupported: "L'export GPX nécessite une version plus récente de l'application. Mettez à jour ZidRun et réessayez.",
    pendingUploads: "{n} sortie en attente d'envoi",
    retryUpload: "Réessayer l'envoi",
    shareRun: "Partager cette sortie publiquement",
    shareHint: "Les sorties publiques apparaissent dans les classements ZidRun de votre wilaya.",
    publicLabel: "Public",
    privateLabel: "Privé",
    injuryHistory: "Antécédents de blessures",
    injuryHistoryHint: "Blessures précédentes, même guéries.",
    currentInjury: "Blessures ou limitations actuelles",
    chronicConditions: "Problèmes de santé persistants",
    chronicHint: "Sélectionnez ce qui s'applique pour que le coach garde votre plan sûr.",
    healthNotes: "Médicaments ou autres notes de santé",
    consentLabel: "Je comprends que le Coach ZidRun fournit des conseils d'entraînement, pas un avis médical, et j'accepte de partager ces informations pour personnaliser mon plan.",
    consentRequired: "Veuillez confirmer pour continuer.",
    trialBadge: "Essai gratuit",
    trialEndsIn: "L'essai se termine le {date}",
    subscribedUntil: "Abonné jusqu'au {date}",
    dailyUsageLabel: "Aujourd'hui {used}/{limit}",
    subscriptionRequiredTitle: "Votre essai gratuit est terminé",
    subscriptionRequiredText: "Abonnez-vous à 790 DA/mois, 1 990 DA pour 3 mois ou 4 900 DA/an pour continuer à utiliser le coach IA. Contactez ZidRun pour activer votre abonnement.",
    requestFailed: "La requête au coach a échoué.",
    goalCreateFailed: "Impossible de créer l'objectif.",
    runSaved: "Sortie enregistrée.",
    runPendingTitle: "Sortie pas encore enregistrée",
    runPendingText: "Si vous quittez cet écran, elle reste en sécurité sur ce téléphone jusqu'à ce que vous choisissiez Enregistrer ou Annuler. Elle ne sera ni envoyée ni supprimée automatiquement.",
    runSaveFailed: "Impossible d'enregistrer la sortie.",
    runUpdateFailed: "Impossible de mettre à jour la sortie.",
    runSavedFeedbackFailed: "Sortie enregistrée, mais le retour du coach a échoué : {error}",
    minTrainingDays: "Choisissez au moins deux jours d'entraînement.",
    formDisclaimer: "Le Coach ZidRun fournit des conseils d'entraînement, pas un diagnostic médical.",
    highPainWarning: "Une douleur élevée suspend les conseils d'entraînement automatiques et recommande une évaluation professionnelle.",
    planSafetyNotice: "Les dates, types et plafonds de distance des séances sont appliqués par les règles de sécurité ZidRun.",
    gpsRunLabel: "Sortie GPS",
    manualRunLabel: "Sortie manuelle",
    details: "Détails",
    runDetailsStats: "Résumé de la sortie",
    runDetailsInsightTitle: "Lecture de la performance",
    runDetailsInsightSteady: (pace: string) => `Un effort maîtrisé à ${pace}/km. Votre allure est régulière : une bonne base pour la prochaine séance.`,
    runDetailsInsightFastFinish: (pace: string) => `Vous avez fini plus vite à ${pace}/km. Une bonne relance — gardez-la fluide, sans forcer.`,
    runDetailsInsightVariable: "Votre allure a varié aujourd'hui. Prenez les passages faciles comme récupération et gardez la prochaine sortie légère.",
    runDetailsRecommendationTitle: "Prochaine étape",
    runDetailsRecommendationEasy: "Gardez les prochaines 24 heures faciles : hydratez-vous, mangez normalement et bougez doucement si vos jambes sont lourdes.",
    runDetailsRecommendationRest: "Faites de la récupération votre prochaine séance. Un jour de repos ou une marche facile aidera votre corps à assimiler le travail.",
    runDetailsHighlights: "Points forts",
    runDetailsRoute: "Parcours",
    runDetailsNoRoute: "Aucun parcours GPS n'a été enregistré pour cette sortie.",
    runDetailsEffort: "Effort",
    runDetailsHeartRate: "Fréquence cardiaque moy.",
    runDetailsCadence: "Cadence",
    runDetailsElevation: "Dénivelé",
    runDetailsCalories: "Calories",
    visibility: "Visibilité",
    runTitle: "Titre",
    runTitlePlaceholder: "ex. Sortie matinale, côtes…",
    description: "Description",
    descriptionPlaceholder: "Comment s'est passée la sortie ? À retenir…",
    deleteRun: "Supprimer",
    deleteRunTitle: "Supprimer cette sortie ?",
    deleteRunText: "La sortie et toutes ses données seront supprimées définitivement. Action irréversible.",
    deletePhotoTitle: "Supprimer cette photo ?",
    deletePhotoText: "La photo sera retirée de cette sortie.",
    confirmDelete: "Supprimer",
    cancel: "Annuler",
    photos: "Photos",
    addPhoto: "Ajouter une photo",
    photoHelp: "JPG, PNG, WebP ou GIF. Jusqu'à 6, 5 Mo max chacune.",
    photoUploading: "Envoi…",
    removePhoto: "Supprimer la photo",
    viewPhoto: "Voir la photo",
    photoUploadFailed: "Impossible d'envoyer la photo. Essayez une image plus petite.",
    saving: "Enregistrement…",
    safetyTitle: "Limite de sécurité",
    safetyText: "Le Coach ZidRun peut expliquer les tendances d'entraînement et proposer des séances prudentes. Il ne diagnostique pas les blessures et ne remplace pas un avis médical professionnel.",
    storedContext: "Contexte enregistré",
    storedItems: ["Objectif et disponibilités", "Sorties récentes et tendances globales", "Plan actuel et signaux de sécurité"],
    requiredField: "Veuillez compléter : {field}",
    invalidField: "Veuillez saisir un {field} valide.",
    challengeTitle: "Défi de la semaine",
    challengeRuns: "Sorties",
    challengeDistance: "Distance",
    streakLabel: "Semaines d'affilée",
    streakNone: "Courez cette semaine pour lancer une série.",
    streakActive: "Continuez — ne cassez pas la série !",
    tipTitle: "Conseil du coach",
    newTip: "Autre conseil",
    suggestionsTitle: "Vous ne savez pas quoi demander ? Essayez ceci",
    tips: [
      "Échauffez-vous avec 5 minutes de footing léger et des balancements de jambes avant chaque sortie pour éviter les blessures.",
      "Suivez la règle des 10 % : n'augmentez pas votre distance hebdomadaire de plus de 10 % pour éviter les blessures de surmenage.",
      "Récupérez en étirant mollets, ischio-jambiers et quadriceps après chaque sortie.",
      "Changez vos chaussures tous les 600–800 km — des semelles usées causent souvent des douleurs au genou et au tibia.",
      "Hydratez-vous avant, pendant et après les sorties longues, et portez des vêtements respirants.",
      "Les sorties faciles doivent rester conversationnelles — si vous ne pouvez pas parler, ralentissez.",
      "Privilégiez le sommeil : la plupart des progrès se font pendant la récupération, pas pendant la course."
    ],
    suggestedQuestions: [
      "Comment éviter les blessures en augmentant ma distance ?",
      "Que manger avant et après une sortie longue ?",
      "J'ai mal au genou après avoir couru — que faire ?",
      "Comment améliorer mon allure en toute sécurité ?",
      "Quelle routine d'échauffement et d'étirements adopter ?",
      "Combien de jours de repos me faut-il chaque semaine ?"
    ],
    pushPromptTitle: "Activer les rappels de course",
    pushPromptText: "Recevez une notification et un e-mail lorsque vous n'avez pas couru depuis un moment, pour garder votre régularité.",
    pushEnable: "Activer les rappels",
    pushDenied: "Les notifications sont bloquées. Activez-les dans les réglages de votre navigateur.",
    pushFailed: "Impossible d'activer les notifications. Veuillez réessayer.",
    dismiss: "Ignorer",
    memory: {
      nav: "Mémoire",
      title: "Ce que votre coach retient",
      intro: "Les faits durables que votre coach garde d'une conversation à l'autre, pour ne pas les redemander. Vous gardez le contrôle : supprimez tout ce qui est faux ou dépassé.",
      healthNote: "Votre coach ne conserve jamais ici de données de santé, de blessure ou médicales.",
      back: "Retour au coach",
      loadFailed: "Impossible de charger la mémoire de votre coach. Veuillez réessayer.",
      actionFailed: "L'action a échoué. Veuillez réessayer.",
      countLabel: "{n} en mémoire",
      emptyTitle: "Rien en mémoire pour l'instant",
      emptyText: "Au fil de vos échanges avec votre coach, il retient les choses durables : quand vous aimez courir, le terrain dont vous disposez, une contrainte à prévoir. Elles apparaîtront ici, à consulter ou supprimer à tout moment.",
      ageToday: "Appris aujourd'hui",
      ageDaysAgo: "Appris il y a {n} jours",
      confirm: "Toujours vrai",
      confirming: "Enregistrement…",
      forget: "Oublier",
      forgetting: "Suppression…",
      export: "Exporter",
      exporting: "Préparation…",
      deleteAll: "Tout supprimer",
      deleteTitle: "Supprimer tout ce que votre coach retient ?",
      deleteText: "Cela efface définitivement chaque fait retenu. Vos courses, plans et objectifs ne sont pas touchés — seulement ce que le coach a appris de vos préférences.",
      deleteConfirm: "Tout supprimer",
      deleting: "Suppression…",
      deleted: "La mémoire de votre coach a été effacée.",
      cancel: "Annuler",
      source: {
        stated: "Vous l'avez dit à votre coach",
        inferred: "Votre coach l'a remarqué",
        derived: "D'après votre entraînement",
        humanCoach: "De la part de votre coach"
      },
      kind: {
        preference: "Préférence",
        coachingTone: "Style de coaching",
        schedule: "Horaires",
        terrain: "Terrain",
        constraint: "Contrainte",
        commitment: "Engagement",
        strategyWorked: "Ce qui marche pour vous",
        strategyFailed: "Ce qui n'a pas marché",
        rejectedSuggestion: "Conseil que vous avez refusé",
        coachNote: "Note du coach"
      }
    }
  },
  ar: {
    eyebrow: "مدرب ZidRun",
    title: "تدرّب بخطوة تالية واضحة",
    intro: "حدّد هدفك، وسجّل كل حصة، واحصل على خطة متدرّجة مبنية على تدريبك الأخير.",
    overview: "نظرة عامة",
    plan: "الخطة",
    runs: "الجريات",
    runOverviewTitle: "أسبوعك فالريتم",
    runOverviewSub: "شوف التقدّم تاعك بلا تعقيد",
    runOverviewLatest: "آخر جَرية",
    runOverviewBrowse: "شوف كامل الجريات",
    runOverviewEmpty: "أول جَرية تاعك تبان هنا.",
    runOverviewStreak: "أسابيع متتابعة",
    runOverviewRecords: "أحسن أرقامك",
    runOverviewLongest: "الأطول",
    runOverviewBestPace: "أحسن ريتم",
    runOverviewTotalDistance: "المسافة الكاملة",
    runOverviewHighlights: "الحوايج المليحة",
    runOverviewHighlightCount: (count: number) => `${count} محققين`,
    runCountSummary: (count: number, distance: number) => `${count} جريات · ${distance.toFixed(1)} كم`,
    coach: "المدرب",
    setupTitle: "أنشئ هدف الجري",
    setupText: "تحدّد أيامك المتاحة وحجم تدريبك الأخير حدود الخطة الآمنة.",
    saveGoal: "إنشاء الهدف",
    editGoal: "تعديل الهدف",
    editGoalTitle: "تعديل هدفك",
    editGoalText: "غيّر التفاصيل التي تريدها أدناه. ستعتمد خطتك القادمة على إجاباتك الجديدة.",
    saveChanges: "حفظ التغييرات",
    goalType: "الهدف",
    targetDate: "تاريخ الهدف",
    targetDateFuture: "يجب أن يكون التاريخ المستهدف في المستقبل.",
    customGoalRequired: "يرجى وصف هدفك المخصّص.",
    trainingDaysInvalid: "اختر بين 2 و7 أيام تدريب.",
    longRunDayInvalid: "يجب أن يكون يوم الجري الطويل أحد أيام تدريبك.",
    fieldInvalid: "يرجى التحقق من الحقل المحدد والمحاولة مرة أخرى.",
    targetDistance: "المسافة المستهدفة (كم)",
    targetTime: "الوقت المستهدف (HH:MM:SS)",
    experience: "الخبرة",
    weeklyDistance: "المسافة الأسبوعية الحالية (كم)",
    trainingDays: "أيام التدريب المتاحة",
    longRunDay: "يوم الحصة الطويلة",
    constraints: "قيود التدريب",
    injuryNotes: "الإصابات أو الملاحظات الصحية",
    responseLanguage: "لغة المدرب",
    currentGoal: "الهدف الحالي",
    target: "الهدف",
    thisWeek: "هذا الأسبوع",
    last28: "آخر 28 يومًا",
    avgPace: "متوسط الوتيرة",
    fatigue: "أعلى مستوى من التعب",
    nextWorkout: "الحصة القادمة",
    noWorkout: "أنشئ خطة أسبوعية لعرض الحصة القادمة.",
    recentCoach: "آخر مراجعة للمدرب",
    noReview: "لا توجد مراجعة بعد.",
    loadOlder: "تحميل الرسائل الأقدم",
    loadingOlder: "جارٍ التحميل…",
    historyStart: "لقد وصلت إلى بداية سجلك.",
    humanNote: "من مدربك",
    generatePlan: "إنشاء خطة أسبوعية",
    reviewPlan: "تحضير الأسبوع القادم",
    generating: "المدرب يحضر خطتك...",
    acceptPlan: "اعتماد الخطة",
    activePlan: "الخطة النشطة",
    today: "اليوم",
    planEndedTitle: "لم تُخطَّط لهذا الأسبوع بعد",
    planEndedText: "انتهى أسبوع خطتك النشطة. أنشئ خطة هذا الأسبوع للحصول على حصة اليوم وتذكيراتك اليومية.",
    workoutDone: "تم",
    workoutMissed: "فائتة",
    planThisWeek: "خطتك هذا الأسبوع",
    adherenceComplete: "مكتملة",
    adherencePlanned: "المخطط",
    viewPlan: "عرض الخطة",
    noActivePlanTitle: "لا توجد خطة نشطة",
    noActivePlanText: "سجّل جرياتك بحرية، أو أنشئ خطة لمتابعة أسبوعك.",
    adherenceMissedRow: "متتالية فائتة",
    cantToday: "لا أستطيع اليوم",
    moveWorkout: "تأجيل",
    skipTitle: "لا بأس — ما الذي حدث؟",
    skipEncourage: "تفويت حصة واحدة أمر عادي. إخباري بالسبب يساعدني على تعديل ما يليها.",
    skipNoReason: "تخطٍّ فقط",
    skipReasonSchedule: "الجدول",
    skipReasonFatigue: "متعب جدًا",
    skipReasonPain: "ألم / أعراض",
    skipReasonWeather: "الطقس",
    skipReasonIllness: "مرض",
    skipReasonTravel: "سفر",
    skipReasonMotivation: "لا رغبة",
    skipReasonOther: "أخرى",
    moveTitle: "إلى أي يوم؟",
    actionCancel: "إلغاء",
    savingAction: "جارٍ الحفظ…",
    skippedReasonLabel: "السبب",
    completionPartial: "جزئية",
    completionEasier: "أسهل من المخطط",
    completionHarder: "أصعب من المخطط",
    matchAutoLinked: "احتُسبت كـ «{title}».",
    matchNotThisWorkout: "ليست هذه الحصة؟",
    matchSuggestQuestion: "هل كانت هذه حصتك «{title}»؟",
    matchConfirmYes: "نعم، هي",
    matchFreeRun: "لا، جري حر",
    missedAskReason: "فوّتّ هذه الحصة — ما الذي حدث؟",
    logThisRun: "سجّل هذا الجري",
    restDayTitle: "يوم راحة",
    restDayText: "التعافي جزء من التدريب — خذ راحتك اليوم.",
    todayDoneTitle: "حصة اليوم اكتملت",
    todayDoneText: "أحسنت. تعافَ جيدًا للحصة القادمة.",
    noSessionToday: "لا توجد حصة مقررة اليوم.",
    trainingSoFar: "تدريبك حتى الآن",
    freeRunnerIntro: "نظرة على تدريبك الفعلي — دون الحاجة إلى خطة بعد.",
    freeRunnerRunsLabel: "آخر 4 أسابيع",
    freeRunnerRunsValue: "{count} جريات",
    freeRunnerInvite: "أتريد خطة مبنية على هذا؟",
    buildMyPlan: "أنشئ خطتي",
    draftPlan: "الخطة المقترحة",
    logRun: "تسجيل حصة",
    durationMinutes: "المدة (دقيقة)",
    distance: "المسافة (كم)",
    startedAt: "التاريخ والوقت",
    effort: "المجهود",
    runFatigue: "التعب",
    pain: "الألم",
    elevation: "الارتفاع المكتسب (م)",
    heartRate: "متوسط نبض القلب",
    symptoms: "الأعراض",
    notes: "ملاحظات الحصة",
    analyzeNow: "الحصول على رأي المدرب بعد الحفظ",
    saveRun: "حفظ الحصة",
    savingRun: "جار الحفظ...",
    runHistory: "آخر الجريات",
    searchRuns: "قلّب على جَرية",
    filterAll: "كامل",
    filterGps: "GPS",
    filterManual: "يدوي",
    filterThisMonth: "هذا الشهر",
    noFilteredRuns: "ما لقيـنا حتى جَرية بهاذ الفلاتر.",
    runSavedJustNow: "تحفظت دروك",
    noRuns: "لم تسجل أي حصة بعد.",
    sleep: "النوم",
    sleepHeading: "سجل النوم",
    sleepIntro: "تابع لياليك — فالنوم الجيد هو الوقت الذي يتحوّل فيه التدريب إلى لياقة.",
    logSleep: "تسجيل نوم",
    sleepModeHours: "ساعات",
    sleepModeTimes: "الأوقات",
    sleepModeText: "وصف",
    sleepHoursLabel: "ساعات النوم",
    sleepBedTime: "وقت النوم",
    sleepWakeTime: "وقت الاستيقاظ",
    sleepTextLabel: "صف نومك (بأي لغة)",
    sleepTextPlaceholder: "مثال: نمت حوالي 7 ساعات، أو من 11 ليلاً إلى 6 صباحاً",
    sleepNight: "الليلة",
    sleepNoteLabel: "ملاحظة (اختياري)",
    saveSleep: "حفظ",
    savingSleep: "جارٍ الحفظ…",
    sleepSaved: "تم حفظ النوم.",
    sleepSaveFailed: "تعذر حفظ النوم.",
    noSleep: "لم تسجل أي نوم بعد.",
    sleepAvgLabel: "متوسط 7 ليالٍ",
    sleepAiBadge: "ذكاء",
    hoursUnit: "س",
    subscribeTitle: "اشتراك المدرب الذكي",
    subscribeIntro: "اشترك لمواصلة التدريب مع مدربك الذكي الشخصي.",
    statusTrial: "فترة تجريبية مجانية",
    statusTrialEndsOn: "تنتهي في {date}",
    statusTrialEnded: "انتهت فترتك التجريبية المجانية.",
    statusSubscribed: "مشترك",
    statusSubscribedUntil: "حتى {date}",
    statusBlocked: "اشترك لفتح المدرب الذكي.",
    trialBannerDaysLeft: "تبقّى {days} أيام من فترتك التجريبية المجانية",
    trialBannerLastDay: "آخر يوم من فترتك التجريبية المجانية",
    trialBannerText: "اشترك للاحتفاظ بمدربك الذكي بعد الفترة التجريبية ومواصلة تقدّمك.",
    trialBannerCta: "اشترك",
    choosePlan: "اختر باقة",
    planMonthly: "شهري",
    planThreeMonths: "3 أشهر",
    planYearly: "سنوي",
    planMonthsSuffix: "شهر",
    payHowTitle: "طريقة الدفع",
    payBaridi: "بريدي موب",
    payCcp: "الحساب الجاري البريدي",
    payCcpKey: "المفتاح",
    payNoDetails: "ستُرسل إليك تفاصيل الدفع قريبًا.",
    methodQuestion: "كيف دفعت؟",
    methodBaridi: "بريدي موب",
    methodCcp: "الحساب الجاري البريدي",
    proofFieldLabel: "لقطة شاشة للدفع",
    proofFieldHelp: "ارفع لقطة شاشة واضحة للتحويل. JPG/PNG، بحد أقصى 5 ميغابايت.",
    submitRequest: "إرسال للمراجعة",
    submittingRequest: "جارٍ الإرسال…",
    requestUnderReview: "دفعتك قيد المراجعة. سنفعّل اشتراكك قريبًا.",
    requestDeclined: "تم رفض طلبك الأخير. يرجى إرسال دفعة جديدة أدناه.",
    subHistoryTitle: "سجل الاشتراكات",
    subHistoryEmpty: "لا توجد اشتراكات بعد.",
    subStatusActive: "نشط",
    subStatusExpired: "منتهٍ",
    subStatusCancelled: "ملغى",
    subStartsLabel: "البداية",
    subEndsLabel: "النهاية",
    amountLabel: "المبلغ",
    currencyDa: "دج",
    backToCoach: "العودة إلى المدرب",
    manageSubscription: "إدارة الاشتراك",
    withdrawRequest: "إلغاء الطلب",
    cancelSubscription: "إلغاء الاشتراك",
    analyzeRun: "تحليل الحصة",
    viewAnalysis: "تحليل المدرب",
    askTitle: "اسأل مدربك",
    askPlaceholder: "كيف أتعامل مع حصتي القادمة؟",
    ask: "اسأل المدرب",
    record: "سجّل ملاحظة صوتية",
    recordStop: "إيقاف التسجيل",
    recording: "جارٍ التسجيل… اضغط للإيقاف.",
    transcribing: "جارٍ نسخ ملاحظتك…",
    transcribeError: "تعذّر النسخ. الرجاء الكتابة بدلاً من ذلك.",
    micDenied: "تم رفض الوصول إلى الميكروفون.",
    thinking: "المدرب يراجع تدريبك...",
    professional: "يوصى باستشارة مختص",
    retry: "إعادة المحاولة",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    days: ["أحد", "اثن", "ثلا", "أرب", "خمي", "جمع", "سبت"],
    dayNames: ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    stepWord: "خطوة",
    ofWord: "من",
    next: "التالي",
    back: "رجوع",
    optional: "اختياري",
    optionalDetails: "تفاصيل اختيارية",
    stepGoalLabel: "الهدف",
    stepBackgroundLabel: "الخلفية",
    stepAvailabilityLabel: "التوفر",
    stepHealthLabel: "الصحة",
    stepReviewLabel: "مراجعة",
    goalStepTitle: "لماذا تتدرّب؟",
    backgroundStepTitle: "خلفيتك في الجري",
    backgroundStepText: "يساعد هذا المدرب على تحديد حِمل بداية آمن وواقعي.",
    availabilityStepTitle: "متى يمكنك التدريب؟",
    healthStepTitle: "الصحة والسلامة",
    healthStepText: "شارك ما يلزم لإبقاء خطتك آمنة. هذا اختياري ويُستخدم فقط لتخصيص تدريبك.",
    reviewStepTitle: "مراجعة وتأكيد",
    yearsRunning: "سنوات الجري المنتظم",
    peakWeeklyDistance: "أعلى مسافة أسبوعية وصلت إليها (كم)",
    longestRecentRun: "أطول حصة حديثة (كم)",
    recentRaceResult: "نتيجة سباق أو اختبار حديث",
    recentRaceResultHint: "مثال: 10 كم في 52:00 الشهر الماضي",
    restingHeartRate: "نبض القلب أثناء الراحة (نبضة/دقيقة)",
    weight: "وزن الجسم (كغ)",
    weightHint: "يُستخدم لتقدير السعرات الحرارية المحروقة.",
    height: "الطول (سم)",
    heightHint: "يُستخدم مع الوزن لفهم بنية الجسم.",
    sex: "الجنس",
    sexMale: "ذكر",
    sexFemale: "أنثى",
    birthDate: "تاريخ الميلاد",
    dobDay: "اليوم",
    dobMonth: "الشهر",
    dobYear: "السنة",
    months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
    hoursLabel: "ساعات",
    minutesLabel: "دقائق",
    secondsLabel: "ثوانٍ",
    recordRun: "سجّل جَرية",
    recordHint: "تتبّع GPS لايف",
    recordingStatus: "راه يسجّل",
    pausedStatus: "موقوف شوية",
    holdToStart: "شدّ باش تبدا",
    holdingToStart: "باقي شاد…",
    startRun: "بدا",
    pause: "حبس شوية",
    resume: "كمّل",
    finishRun: "حبس الجَرية",
    discard: "ما تحفظش",
    statDistance: "المسافة",
    statTime: "المدة",
    statMovingTime: "وقت الحركة",
    statPace: "الريتم",
    statCurrentPace: "الريتم دروك",
    statAvgPace: "معدّل الريتم",
    statElevation: "الطلوع",
    statCalories: "السعرات",
    gpsAcquiring: "راه يقلب على GPS…",
    gpsWarmup: "GPS راه يثبت. الخريطة تبان كي يثبت الموقع باش ما نعرضوش بلاصة قديمة.",
    gpsError: "ما قدرناش نحددو بلاصتك. فعّل الموقع لتطبيق ZidRun.",
    openSettings: "حلّ الإعدادات",
    runTooShort: "الجَرية قصيرة بزاف للحفظ (لازم 100 م ودقيقة على الأقل).",
    savedOffline: "تحفظت فالتليفون — تترفع وحدها كي يرجع النت.",
    recorderCrashTitle: "المسجّل حبّس",
    recorderCrashText: "صرات مشكلة فمسجّل الجَرية. غالبًا بقات جَرية قديمة عالقة — مسحها يصلّحها.",
    recorderCrashReset: "مسح وعاود حلّ",
    recoverTitle: "نكملو الجَرية؟",
    recoverText: "لقينا جَرية ما كملتش فهاد التليفون. كمّل من وين حبست ولا مسحها.",
    recoverResume: "كمّل الجَرية",
    recoverDiscard: "مسحها",
    statGps: "GPS",
    gpsWeak: "ضعيف",
    gpsFair: "مليح",
    gpsStrong: "قوي",
    bgTitle: "خلي التسجيل يخدم والشاشة طافية",
    bgText: "سمح لـ ZidRun يتجاهل تحسين البطارية باش أندرويد ما يوقفش GPS كي تطفى الشاشة.",
    bgEnable: "سمح بالتسجيل فالخلفية",
    bgEnabled: "التسجيل فالخلفية خدام.",
    bgLocationTitle: "الموقع راه مطفي",
    bgLocationText: "سمح بالوصول للموقع باش ZidRun يسجّل الجَرية حتى كي تطفى الشاشة.",
    bgLocationCta: "فعّل الموقع",
    statCadence: "خطوات/دقيقة",
    nonFootWarnTitle: "هاذي ما تبانش جَرية على الرجلين",
    nonFootWarnCadence: "إيقاع خطواتك منخفض جدًا مقارنةً بهذه السرعة — يبدو أنّ هذا سُجِّل على عجلات أو بمحرّك (سيارة، درّاجة، سكوتر، لوح تزلّج…)، وليس على الأقدام. يمكنك حفظه، لكن سيُستبعد من إحصائياتك وأرقامك القياسية والمدرّب — ويمكنك حذفه في أي وقت.",
    nonFootWarnSpeed: "كانت سرعتك أعلى مما يمكن لأي شخص أن يجري به على قدميه — يبدو أنّ هذا سُجِّل على عجلات أو بمحرّك (سيارة، درّاجة، سكوتر، لوح تزلّج…). يمكنك حفظه، لكن سيُستبعد من إحصائياتك وأرقامك القياسية والمدرّب — ويمكنك حذفه في أي وقت.",
    nonFootBadge: "غالبًا ليس على الأقدام",
    excludedFromStatsBadge: "مستبعد من الإحصائيات",
    excludedFromStatsHint: "لا يبدو أنّ هذا النشاط كان على الأقدام، لذا فهو مستبعد من إحصائياتك وأرقامك القياسية والمدرّب. يمكنك حذفه في أي وقت.",
    splitsLabel: "الوقت فكل كيلومتر",
    profileElevation: "الطلوع",
    profilePace: "الريتم",
    splitFastest: "الأسرع",
    splitSlowest: "الأبطأ",
    gpxExport: "GPX",
    gpxPreparing: "جارٍ تحضير GPX…",
    gpxSaveDialog: "حفظ ملف GPX أو مشاركته",
    gpxChooseDestination: "ملف GPX جاهز — اختر تطبيقًا أو مجلدًا لحفظه.",
    gpxDownloadStarted: "بدأ تنزيل ملف GPX.",
    gpxExportFailed: "لم يتم تصدير ملف GPX: {reason}",
    gpxUnknownError: "خطأ غير معروف. حاول مرة أخرى.",
    gpxNativeUnsupported: "تصدير GPX يتطلب نسخة أحدث من التطبيق. يرجى تحديث ZidRun والمحاولة مرة أخرى.",
    pendingUploads: "{n} جريات مازالو يستناو الرفع",
    retryUpload: "عاود الرفع",
    shareRun: "شارك هاذ الجَرية للناس",
    shareHint: "الجريات العمومية يقدرو يشوفوها فالترتيب تاع ولايتك.",
    publicLabel: "عمومية",
    privateLabel: "خاصة",
    injuryHistory: "تاريخ الإصابات السابقة",
    injuryHistoryHint: "إصابات سابقة حتى وإن تعافيت منها.",
    currentInjury: "إصابات أو قيود حالية",
    chronicConditions: "حالات صحية مزمنة",
    chronicHint: "اختر ما ينطبق ليحافظ المدرب على خطتك آمنة.",
    healthNotes: "أدوية أو ملاحظات صحية أخرى",
    consentLabel: "أفهم أن مدرب ZidRun يقدّم إرشادات تدريبية وليست نصيحة طبية، وأوافق على مشاركة هذه المعلومات لتخصيص خطتي.",
    consentRequired: "يرجى التأكيد للمتابعة.",
    trialBadge: "تجربة مجانية",
    trialEndsIn: "تنتهي التجربة في {date}",
    subscribedUntil: "مشترك حتى {date}",
    dailyUsageLabel: "اليوم {used}/{limit}",
    subscriptionRequiredTitle: "انتهت تجربتك المجانية",
    subscriptionRequiredText: "اشترك مقابل 790 دج شهريًا، أو 1990 دج لمدة 3 أشهر، أو 4900 دج سنويًا لمواصلة استخدام مدرب الذكاء الاصطناعي. تواصل مع ZidRun لتفعيل اشتراكك.",
    requestFailed: "فشل طلب المدرب.",
    goalCreateFailed: "تعذّر إنشاء الهدف.",
    runSaved: "تم حفظ الحصة.",
    runPendingTitle: "الحصة لم تُحفظ بعد",
    runPendingText: "إذا غادرت هذه الشاشة، ستبقى الحصة بأمان على هاتفك حتى تختار الحفظ أو الحذف. لن يتم رفعها أو حذفها تلقائيًا.",
    runSaveFailed: "تعذّر حفظ الحصة.",
    runUpdateFailed: "تعذّر تحديث الحصة.",
    runSavedFeedbackFailed: "تم حفظ الحصة، لكن تعذّر الحصول على رأي المدرب: {error}",
    minTrainingDays: "اختر يومين تدريب على الأقل.",
    formDisclaimer: "يقدّم مدرب ZidRun إرشادات تدريبية وليس تشخيصًا طبيًا.",
    highPainWarning: "الألم الشديد يوقف النصائح التدريبية التلقائية ويوصي بتقييم مختص.",
    planSafetyNotice: "تواريخ الحصص وأنواعها وحدود المسافة تُطبَّق وفق قواعد سلامة ZidRun.",
    gpsRunLabel: "حصة GPS",
    manualRunLabel: "حصة يدوية",
    details: "التفاصيل",
    runDetailsStats: "ملخّص الجَرية",
    runDetailsInsightTitle: "كيف دارت الجَرية",
    runDetailsInsightSteady: (pace: string) => `خدمة متوازنة بــ ${pace}/كم. الريتم كان ثابت، وهذا مليح للجَرية الجاية.`,
    runDetailsInsightFastFinish: (pace: string) => `كمّلت أسرع بــ ${pace}/كم. مليح زدت فالآخر — خليه بسلاسة وما تضغطش بزاف.`,
    runDetailsInsightVariable: "الريتم تبدّل اليوم. استعمل المقاطع الساهلة باش ترتاح وخلي الجَرية الجاية خفيفة.",
    runDetailsRecommendationTitle: "الخطوة الجاية",
    runDetailsRecommendationEasy: "خلي الـ24 ساعة الجاية خفاف: اشرب الماء، كل مليح، ودير حركة خفيفة إذا حسّيت رجليك ثقال.",
    runDetailsRecommendationRest: "خلي الاسترجاع هو الحصة الجاية. نهار راحة ولا مشية خفيفة يعاونو جسمك يستافد من الخدمة.",
    runDetailsHighlights: "الحوايج المليحة",
    runDetailsRoute: "المسار",
    runDetailsNoRoute: "ما تسجّل حتى مسار GPS فهاذ الجَرية.",
    runDetailsEffort: "المجهود",
    runDetailsHeartRate: "معدّل نبض القلب",
    runDetailsCadence: "الخطوات/دقيقة",
    runDetailsElevation: "الطلوع",
    runDetailsCalories: "السعرات",
    visibility: "الظهور",
    runTitle: "العنوان",
    runTitlePlaceholder: "مثال: جري صباحي، تكرارات صعود…",
    description: "الوصف",
    descriptionPlaceholder: "كيف كانت الحصة؟ أي شيء يستحق التذكّر…",
    deleteRun: "حذف الحصة",
    deleteRunTitle: "حذف هذه الحصة؟",
    deleteRunText: "سيؤدي هذا إلى حذف الحصة وكل بياناتها نهائيًا. لا يمكن التراجع.",
    deletePhotoTitle: "إزالة هذه الصورة؟",
    deletePhotoText: "ستتم إزالة الصورة من هذه الحصة.",
    confirmDelete: "حذف",
    cancel: "إلغاء",
    photos: "الصور",
    addPhoto: "إضافة صورة",
    photoHelp: "JPG أو PNG أو WebP أو GIF. حتى 6 صور، 5 ميغابايت لكل صورة.",
    photoUploading: "جارٍ الرفع…",
    removePhoto: "حذف الصورة",
    viewPhoto: "عرض الصورة",
    photoUploadFailed: "تعذّر رفع الصورة. جرّب صورة أصغر.",
    saving: "جارٍ الحفظ…",
    safetyTitle: "حدود السلامة",
    safetyText: "يمكن لمدرب ZidRun شرح أنماط التدريب واقتراح حصص حذرة. لا يشخّص الإصابات ولا يحل محل الرعاية الطبية المختصة.",
    storedContext: "السياق المخزّن",
    storedItems: ["الهدف والتوفر", "الحصص الأخيرة والاتجاهات العامة", "الخطة الحالية وإشارات السلامة"],
    requiredField: "يرجى إكمال: {field}",
    invalidField: "يرجى إدخال {field} صحيح.",
    challengeTitle: "تحدي هذا الأسبوع",
    challengeRuns: "الحصص",
    challengeDistance: "المسافة",
    streakLabel: "أسابيع متتالية",
    streakNone: "اجرِ هذا الأسبوع لتبدأ سلسلة.",
    streakActive: "واصل — لا تكسر السلسلة!",
    tipTitle: "نصيحة المدرب",
    newTip: "نصيحة أخرى",
    suggestionsTitle: "لا تعرف ماذا تسأل؟ جرّب أحد الاقتراحات التالية",
    tips: [
      "ابدأ بإحماء 5 دقائق من الجري الخفيف وتمارين تأرجح الساق قبل كل حصة لتفادي الإصابات.",
      "اتبع قاعدة الـ10٪: لا تزد مسافتك الأسبوعية بأكثر من 10٪ لتجنب إصابات الإجهاد.",
      "قم بالتهدئة وإطالة عضلات الساق والفخذ بعد كل حصة لتسريع الاستشفاء.",
      "غيّر حذاء الجري كل 600–800 كم — النعل المهترئ سبب شائع لآلام الركبة والساق.",
      "اشرب الماء قبل الجري الطويل وأثناءه وبعده، والبس ملابس مريحة تسمح بالتهوية.",
      "يجب أن تكون الحصص السهلة بوتيرة تسمح بالحديث — إن لم تستطع الكلام فأبطئ.",
      "أعطِ النوم أولوية: معظم تحسّن لياقتك يحدث أثناء الاستشفاء وليس أثناء الجري."
    ],
    suggestedQuestions: [
      "كيف أتجنب الإصابات مع زيادة المسافة؟",
      "ماذا آكل قبل الجري الطويل وبعده؟",
      "تؤلمني ركبتي بعد الجري — ماذا أفعل؟",
      "كيف أحسّن وتيرتي بأمان؟",
      "ما روتين الإحماء والإطالة الجيد؟",
      "كم يوم راحة أحتاج كل أسبوع؟"
    ],
    pushPromptTitle: "تفعيل تذكيرات الجري",
    pushPromptText: "احصل على إشعار وبريد إلكتروني عندما تنقطع عن الجري فترة، لتحافظ على انتظامك.",
    pushEnable: "تفعيل التذكيرات",
    pushDenied: "الإشعارات محظورة. فعّلها من إعدادات المتصفح.",
    pushFailed: "تعذّر تفعيل الإشعارات. حاول مرة أخرى.",
    dismiss: "تجاهل",
    memory: {
      nav: "الذاكرة",
      title: "ما يتذكره مدربك",
      intro: "حقائق دائمة يحتفظ بها مدربك بين المحادثات حتى لا يسألك مرتين. أنت المتحكم — احذف أي شيء خاطئ أو لم يعد صحيحًا.",
      healthNote: "لا يحفظ مدربك هنا أبدًا أي بيانات صحية أو إصابات أو معلومات طبية.",
      back: "العودة إلى المدرب",
      loadFailed: "تعذّر تحميل ذاكرة مدربك. حاول مرة أخرى.",
      actionFailed: "لم تنجح العملية. حاول مرة أخرى.",
      countLabel: "{n} في الذاكرة",
      emptyTitle: "لا شيء في الذاكرة بعد",
      emptyText: "مع تحدثك إلى مدربك، سيتذكر الأمور الدائمة: متى تحب الجري، والتضاريس المتاحة لك، وقيدًا يجب مراعاته. ستظهر هنا لمراجعتها أو حذفها في أي وقت.",
      ageToday: "عُرف اليوم",
      ageDaysAgo: "عُرف قبل {n} يومًا",
      confirm: "لا يزال صحيحًا",
      confirming: "جارٍ الحفظ…",
      forget: "نسيان",
      forgetting: "جارٍ الإزالة…",
      export: "تصدير",
      exporting: "جارٍ التحضير…",
      deleteAll: "حذف الكل",
      deleteTitle: "حذف كل ما يتذكره مدربك؟",
      deleteText: "سيؤدي ذلك إلى مسح كل حقيقة محفوظة نهائيًا. لن تتأثر جرياتك أو خططك أو أهدافك — فقط ما تعلّمه المدرب عن تفضيلاتك.",
      deleteConfirm: "حذف كل شيء",
      deleting: "جارٍ الحذف…",
      deleted: "تم مسح ذاكرة مدربك.",
      cancel: "إلغاء",
      source: {
        stated: "أخبرت مدربك بذلك",
        inferred: "لاحظ مدربك ذلك",
        derived: "من تدريبك",
        humanCoach: "من مدربك"
      },
      kind: {
        preference: "تفضيل",
        coachingTone: "أسلوب التدريب",
        schedule: "المواعيد",
        terrain: "التضاريس",
        constraint: "قيد",
        commitment: "التزام",
        strategyWorked: "ما ينجح معك",
        strategyFailed: "ما لم ينجح",
        rejectedSuggestion: "نصيحة رفضتها",
        coachNote: "ملاحظة المدرب"
      }
    }
  }
} as const;

export function getCoachCopy(locale: CoachLocale) {
  return copy[locale];
}

export type CoachCopy = ReturnType<typeof getCoachCopy>;

export const goalOptions = [
  ["GENERAL_FITNESS", "General fitness", "Forme générale", "لياقة عامة"],
  ["FIVE_K", "5K", "5 km", "5 كم"],
  ["TEN_K", "10K", "10 km", "10 كم"],
  ["HALF_MARATHON", "Half marathon", "Semi-marathon", "نصف ماراثون"],
  ["MARATHON", "Marathon", "Marathon", "ماراثون"],
  ["TRAIL", "Trail", "Trail", "جري جبلي"],
  ["OTHER", "Other", "Autre", "آخر"]
] as const;

export function localizedOption(option: readonly [string, string, string, string], locale: CoachLocale) {
  return option[locale === "en" ? 1 : locale === "fr" ? 2 : 3];
}

export const chronicConditionOptions = [
  ["NONE", "None", "Aucun", "لا شيء"],
  ["ASTHMA", "Asthma", "Asthme", "الربو"],
  ["DIABETES", "Diabetes", "Diabète", "السكري"],
  ["HYPERTENSION", "High blood pressure", "Hypertension", "ارتفاع ضغط الدم"],
  ["HEART_CONDITION", "Heart condition", "Problème cardiaque", "حالة قلبية"],
  ["THYROID", "Thyroid condition", "Trouble thyroïdien", "اضطراب الغدة الدرقية"],
  ["ANEMIA", "Anemia", "Anémie", "فقر الدم"],
  ["OTHER", "Other", "Autre", "أخرى"]
] as const;
