import type { CoachLocale } from "@/components/coach/types";

const copy = {
  en: {
    eyebrow: "ZidRun Coach",
    title: "Train with a clear next step",
    intro: "Set a goal, log each run, and get a conservative plan grounded in your recent training.",
    overview: "Overview",
    plan: "Plan",
    runs: "Runs",
    coach: "Coach",
    setupTitle: "Create your running goal",
    setupText: "Your availability and recent volume define the safe plan boundaries.",
    saveGoal: "Create goal",
    editGoal: "Edit goal",
    editGoalTitle: "Update your goal",
    editGoalText: "Change any detail below. Your next generated plan will use the new answers.",
    saveChanges: "Save changes",
    goalType: "Goal",
    targetDate: "Target date",
    targetDateFuture: "Target date must be in the future.",
    customGoalRequired: "Please describe your custom goal.",
    trainingDaysInvalid: "Choose between 2 and 7 training days.",
    longRunDayInvalid: "Your long-run day must be one of your training days.",
    fieldInvalid: "Please check the highlighted field and try again.",
    targetDistance: "Target distance (km)",
    targetTime: "Target time (HH:MM:SS)",
    experience: "Experience",
    weeklyDistance: "Current weekly distance (km)",
    trainingDays: "Available training days",
    longRunDay: "Preferred long-run day",
    constraints: "Training constraints",
    injuryNotes: "Injury or health notes",
    responseLanguage: "Coach language",
    currentGoal: "Current goal",
    target: "Target",
    thisWeek: "This week",
    last28: "Last 28 days",
    avgPace: "Average pace",
    fatigue: "Peak fatigue",
    nextWorkout: "Next workout",
    noWorkout: "Generate a weekly plan to see your next workout.",
    recentCoach: "Latest coach review",
    noReview: "No coach review yet.",
    generatePlan: "Generate weekly plan",
    reviewPlan: "Review next week",
    generating: "Coach is preparing your plan...",
    acceptPlan: "Accept plan",
    activePlan: "Active plan",
    today: "Today",
    planEndedTitle: "This week isn't planned yet",
    planEndedText: "Your active plan's week has ended. Generate this week's plan to get today's run and your daily reminders.",
    workoutDone: "Done",
    workoutMissed: "Missed",
    draftPlan: "Draft plan",
    logRun: "Log a run",
    durationMinutes: "Duration (minutes)",
    distance: "Distance (km)",
    startedAt: "Date and time",
    effort: "Effort",
    runFatigue: "Fatigue",
    pain: "Pain",
    elevation: "Elevation gain (m)",
    heartRate: "Average heart rate",
    symptoms: "Symptoms",
    notes: "Run notes",
    analyzeNow: "Get coach feedback after saving",
    saveRun: "Save run",
    savingRun: "Saving run...",
    runHistory: "Recent runs",
    noRuns: "No runs logged yet.",
    sleep: "Sleep",
    sleepHeading: "Sleep log",
    sleepIntro: "Track your nights — good sleep is when training turns into fitness.",
    logSleep: "Log sleep",
    sleepModeHours: "Hours",
    sleepModeTimes: "Times",
    sleepModeText: "Describe",
    sleepHoursLabel: "Hours slept",
    sleepBedTime: "Bed time",
    sleepWakeTime: "Wake time",
    sleepTextLabel: "Describe your sleep (any language)",
    sleepTextPlaceholder: "e.g. slept about 7 hours, or 11pm to 6am",
    sleepNight: "Night",
    sleepNoteLabel: "Note (optional)",
    saveSleep: "Save sleep",
    savingSleep: "Saving…",
    sleepSaved: "Sleep saved.",
    sleepSaveFailed: "Unable to save sleep.",
    noSleep: "No sleep logged yet.",
    sleepAvgLabel: "7-night average",
    sleepAiBadge: "AI",
    hoursUnit: "h",
    subscribeTitle: "AI Coach subscription",
    subscribeIntro: "Subscribe to keep training with your personal AI coach.",
    statusTrial: "Free trial",
    statusTrialEndsOn: "ends {date}",
    statusTrialEnded: "Your free trial has ended.",
    statusSubscribed: "Subscribed",
    statusSubscribedUntil: "until {date}",
    statusBlocked: "Subscribe to unlock the AI coach.",
    choosePlan: "Choose a plan",
    planMonthly: "Monthly",
    planYearly: "Yearly",
    planMonthsSuffix: "mo",
    payHowTitle: "How to pay",
    payBaridi: "BaridiMob",
    payCcp: "CCP",
    payCcpKey: "Key",
    payNoDetails: "Payment details will be shared with you shortly.",
    methodQuestion: "How did you pay?",
    methodBaridi: "BaridiMob",
    methodCcp: "CCP",
    proofFieldLabel: "Payment screenshot",
    proofFieldHelp: "Upload a clear screenshot of your transfer. JPG/PNG, max 5 MB.",
    submitRequest: "Submit for review",
    submittingRequest: "Submitting…",
    requestUnderReview: "Your payment is under review. We'll activate your subscription shortly.",
    requestDeclined: "Your last request was declined. Please submit a new payment below.",
    subHistoryTitle: "Subscription history",
    subHistoryEmpty: "No subscriptions yet.",
    subStatusActive: "Active",
    subStatusExpired: "Expired",
    subStatusCancelled: "Cancelled",
    subStartsLabel: "Start",
    subEndsLabel: "End",
    amountLabel: "Amount",
    currencyDa: "DA",
    backToCoach: "Back to coach",
    manageSubscription: "Manage subscription",
    withdrawRequest: "Cancel request",
    cancelSubscription: "Cancel subscription",
    analyzeRun: "Analyze run",
    viewAnalysis: "Coach analysis",
    askTitle: "Ask your coach",
    askPlaceholder: "How should I approach my next run?",
    ask: "Ask coach",
    record: "Record a voice note",
    recordStop: "Stop recording",
    recording: "Recording… tap to stop.",
    transcribing: "Transcribing your note…",
    transcribeError: "Could not transcribe. Please type instead.",
    micDenied: "Microphone access was denied.",
    thinking: "Coach is reviewing your training...",
    professional: "Professional assessment recommended",
    retry: "Try again",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    stepWord: "Step",
    ofWord: "of",
    next: "Next",
    back: "Back",
    optional: "Optional",
    optionalDetails: "Optional details",
    stepGoalLabel: "Goal",
    stepBackgroundLabel: "Background",
    stepAvailabilityLabel: "Availability",
    stepHealthLabel: "Health",
    stepReviewLabel: "Review",
    goalStepTitle: "What are you training for?",
    backgroundStepTitle: "Your running background",
    backgroundStepText: "This helps the coach set a safe, realistic starting load.",
    availabilityStepTitle: "When can you train?",
    healthStepTitle: "Health & safety",
    healthStepText: "Share anything that should keep your plan safe. This is optional and used only to personalize your training.",
    reviewStepTitle: "Review & confirm",
    yearsRunning: "Years running regularly",
    peakWeeklyDistance: "Highest weekly distance ever (km)",
    longestRecentRun: "Longest recent run (km)",
    recentRaceResult: "Recent race or time trial result",
    recentRaceResultHint: "e.g. 10K in 52:00 last month",
    restingHeartRate: "Resting heart rate (bpm)",
    weight: "Body weight (kg)",
    weightHint: "Used to estimate calories burned.",
    height: "Height (cm)",
    heightHint: "Used with weight for body-composition context.",
    sex: "Sex",
    sexMale: "Male",
    sexFemale: "Female",
    birthDate: "Date of birth",
    dobDay: "Day",
    dobMonth: "Month",
    dobYear: "Year",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    hoursLabel: "Hours",
    minutesLabel: "Minutes",
    secondsLabel: "Seconds",
    recordRun: "Record a run",
    recordHint: "Live GPS tracking",
    startRun: "Start run",
    pause: "Pause",
    resume: "Resume",
    finishRun: "Finish",
    discard: "Discard",
    statDistance: "Distance",
    statTime: "Time",
    statMovingTime: "Moving",
    statPace: "Pace",
    statCurrentPace: "Current pace",
    statAvgPace: "Avg pace",
    statElevation: "Elevation",
    statCalories: "Calories",
    gpsAcquiring: "Acquiring GPS signal…",
    gpsError: "Couldn't get your location. Enable location permission for ZidRun.",
    openSettings: "Open settings",
    runTooShort: "Run is too short to save (needs at least 100 m and 1 min).",
    savedOffline: "Saved on your phone — it will upload automatically when you're back online.",
    recoverTitle: "Resume your run?",
    recoverText: "We found an unfinished run on this phone. Continue where you left off, or discard it.",
    recoverResume: "Resume run",
    recoverDiscard: "Discard",
    statGps: "GPS",
    gpsWeak: "Weak",
    gpsFair: "Fair",
    gpsStrong: "Strong",
    bgTitle: "Keep recording with the screen off",
    bgText: "Allow ZidRun to ignore battery optimization so Android won't pause GPS while your screen is off.",
    bgEnable: "Allow background recording",
    bgEnabled: "Background recording is on.",
    bgLocationTitle: "Location is turned off",
    bgLocationText: "Allow location access so ZidRun can record your run, even with the screen off.",
    bgLocationCta: "Enable location",
    statCadence: "Cadence",
    splitsLabel: "Splits (per km)",
    profileElevation: "Elevation",
    profilePace: "Pace",
    splitFastest: "Fastest",
    splitSlowest: "Slowest",
    pendingUploads: "{n} run waiting to upload",
    retryUpload: "Retry upload",
    shareRun: "Share this run publicly",
    shareHint: "Public runs appear on the ZidRun leaderboards for your wilaya.",
    publicLabel: "Public",
    privateLabel: "Private",
    injuryHistory: "Past injury history",
    injuryHistoryHint: "Previous injuries, even if recovered.",
    currentInjury: "Current injuries or limitations",
    chronicConditions: "Ongoing health conditions",
    chronicHint: "Select any that apply so the coach keeps your plan safe.",
    healthNotes: "Medication or other health notes",
    consentLabel: "I understand ZidRun Coach gives training guidance, not medical advice, and I agree to share this information to personalize my plan.",
    consentRequired: "Please confirm to continue.",
    trialBadge: "Free trial",
    trialEndsIn: "Trial ends {date}",
    subscribedUntil: "Subscribed until {date}",
    dailyUsageLabel: "Today {used}/{limit}",
    subscriptionRequiredTitle: "Your free trial has ended",
    subscriptionRequiredText: "Subscribe for 500 DA/month or 4000 DA/year to keep using the AI coach. Contact ZidRun to activate your subscription.",
    requestFailed: "Coach request failed.",
    goalCreateFailed: "Unable to create goal.",
    runSaved: "Run saved.",
    runSaveFailed: "Unable to save run.",
    runUpdateFailed: "Unable to update run.",
    runSavedFeedbackFailed: "Run saved, but coach feedback failed: {error}",
    minTrainingDays: "Choose at least two training days.",
    formDisclaimer: "ZidRun Coach provides training guidance, not medical diagnosis.",
    highPainWarning: "High pain will pause automated training advice and recommend professional assessment.",
    planSafetyNotice: "Workout dates, types and distance ceilings are enforced by ZidRun safety rules.",
    gpsRunLabel: "GPS run",
    manualRunLabel: "Manual run",
    details: "Details",
    visibility: "Visibility",
    runTitle: "Title",
    runTitlePlaceholder: "e.g. Morning run, hill repeats…",
    description: "Description",
    descriptionPlaceholder: "How did the run feel? Anything worth remembering…",
    deleteRun: "Delete run",
    deleteRunTitle: "Delete this run?",
    deleteRunText: "This permanently removes the run and all its data. This can't be undone.",
    deletePhotoTitle: "Remove this photo?",
    deletePhotoText: "The photo will be removed from this run.",
    confirmDelete: "Delete",
    cancel: "Cancel",
    photos: "Photos",
    addPhoto: "Add photo",
    photoHelp: "JPG, PNG, WebP, or GIF. Up to 6, max 5 MB each.",
    photoUploading: "Uploading…",
    removePhoto: "Remove photo",
    viewPhoto: "View photo",
    photoUploadFailed: "Could not upload the photo. Try a smaller image.",
    saving: "Saving…",
    safetyTitle: "Safety boundary",
    safetyText: "ZidRun Coach can explain training patterns and propose conservative sessions. It does not diagnose injuries or replace professional care.",
    storedContext: "Stored context",
    storedItems: ["Goal and availability", "Recent runs and aggregate trends", "Current plan and safety signals"],
    requiredField: "Please complete: {field}",
    invalidField: "Please enter a valid {field}.",
    challengeTitle: "This week's challenge",
    challengeRuns: "Runs",
    challengeDistance: "Distance",
    streakLabel: "Week streak",
    streakNone: "Run this week to start a streak.",
    streakActive: "Keep it going — don't break the chain!",
    tipTitle: "Coach tip",
    newTip: "Another tip",
    suggestionsTitle: "Not sure what to ask? Try one of these",
    tips: [
      "Warm up with 5 minutes of easy jogging and leg swings before every run to prevent injury.",
      "Follow the 10% rule: don't increase your weekly distance by more than 10% to avoid overuse injuries.",
      "Cool down and stretch your calves, hamstrings, and quads after each run to aid recovery.",
      "Replace running shoes every 600–800 km — worn soles are a common cause of knee and shin pain.",
      "Hydrate before, during, and after long runs, and run in breathable, moisture-wicking clothing.",
      "Easy runs should feel conversational — if you can't talk in full sentences, slow down.",
      "Prioritise sleep: most of your fitness gains happen during recovery, not the run itself."
    ],
    suggestedQuestions: [
      "How can I avoid injury as I increase my distance?",
      "What should I eat before and after a long run?",
      "My knee hurts after running — what should I do?",
      "How do I improve my pace safely?",
      "What's a good warm-up and stretching routine?",
      "How many rest days do I need each week?"
    ],
    pushPromptTitle: "Turn on run reminders",
    pushPromptText: "Get a friendly push and email when you haven't run in a while, so you stay consistent.",
    pushEnable: "Enable reminders",
    pushDenied: "Notifications are blocked. Enable them in your browser settings.",
    pushFailed: "Couldn't enable notifications. Please try again.",
    dismiss: "Dismiss"
  },
  fr: {
    eyebrow: "Coach ZidRun",
    title: "Entraînez-vous avec une prochaine étape claire",
    intro: "Définissez un objectif, enregistrez chaque sortie et recevez un plan prudent basé sur votre entraînement récent.",
    overview: "Aperçu",
    plan: "Plan",
    runs: "Sorties",
    coach: "Coach",
    setupTitle: "Créez votre objectif de course",
    setupText: "Vos disponibilités et votre volume récent définissent les limites du plan.",
    saveGoal: "Créer l'objectif",
    editGoal: "Modifier l'objectif",
    editGoalTitle: "Modifier votre objectif",
    editGoalText: "Changez n'importe quel détail ci-dessous. Votre prochain plan généré utilisera les nouvelles réponses.",
    saveChanges: "Enregistrer",
    goalType: "Objectif",
    targetDate: "Date cible",
    targetDateFuture: "La date cible doit être dans le futur.",
    customGoalRequired: "Veuillez décrire votre objectif personnalisé.",
    trainingDaysInvalid: "Choisissez entre 2 et 7 jours d'entraînement.",
    longRunDayInvalid: "Votre jour de sortie longue doit être un de vos jours d'entraînement.",
    fieldInvalid: "Veuillez vérifier le champ indiqué et réessayer.",
    targetDistance: "Distance cible (km)",
    targetTime: "Temps cible (HH:MM:SS)",
    experience: "Expérience",
    weeklyDistance: "Distance hebdomadaire actuelle (km)",
    trainingDays: "Jours d'entraînement disponibles",
    longRunDay: "Jour préféré pour la sortie longue",
    constraints: "Contraintes d'entraînement",
    injuryNotes: "Blessures ou notes de santé",
    responseLanguage: "Langue du coach",
    currentGoal: "Objectif actuel",
    target: "Cible",
    thisWeek: "Cette semaine",
    last28: "28 derniers jours",
    avgPace: "Allure moyenne",
    fatigue: "Fatigue maximale",
    nextWorkout: "Prochaine séance",
    noWorkout: "Générez un plan hebdomadaire pour voir la prochaine séance.",
    recentCoach: "Dernier bilan du coach",
    noReview: "Aucun bilan du coach pour le moment.",
    generatePlan: "Générer le plan hebdomadaire",
    reviewPlan: "Préparer la semaine suivante",
    generating: "Le coach prépare votre plan...",
    acceptPlan: "Accepter le plan",
    activePlan: "Plan actif",
    today: "Aujourd'hui",
    planEndedTitle: "Cette semaine n'est pas encore planifiée",
    planEndedText: "La semaine de votre plan actif est terminée. Générez le plan de cette semaine pour obtenir la séance du jour et vos rappels quotidiens.",
    workoutDone: "Fait",
    workoutMissed: "Manquée",
    draftPlan: "Plan proposé",
    logRun: "Enregistrer une sortie",
    durationMinutes: "Durée (minutes)",
    distance: "Distance (km)",
    startedAt: "Date et heure",
    effort: "Effort",
    runFatigue: "Fatigue",
    pain: "Douleur",
    elevation: "Dénivelé positif (m)",
    heartRate: "Fréquence cardiaque moyenne",
    symptoms: "Symptômes",
    notes: "Notes de sortie",
    analyzeNow: "Recevoir un retour du coach après l'enregistrement",
    saveRun: "Enregistrer",
    savingRun: "Enregistrement...",
    runHistory: "Sorties récentes",
    noRuns: "Aucune sortie enregistrée.",
    sleep: "Sommeil",
    sleepHeading: "Journal de sommeil",
    sleepIntro: "Suivez vos nuits — c'est pendant un bon sommeil que l'entraînement devient de la forme.",
    logSleep: "Ajouter une nuit",
    sleepModeHours: "Heures",
    sleepModeTimes: "Horaires",
    sleepModeText: "Décrire",
    sleepHoursLabel: "Heures dormies",
    sleepBedTime: "Coucher",
    sleepWakeTime: "Réveil",
    sleepTextLabel: "Décrivez votre sommeil (toute langue)",
    sleepTextPlaceholder: "ex. dormi environ 7 heures, ou 23h à 6h",
    sleepNight: "Nuit",
    sleepNoteLabel: "Note (facultatif)",
    saveSleep: "Enregistrer",
    savingSleep: "Enregistrement…",
    sleepSaved: "Sommeil enregistré.",
    sleepSaveFailed: "Impossible d'enregistrer le sommeil.",
    noSleep: "Aucun sommeil enregistré.",
    sleepAvgLabel: "Moyenne 7 nuits",
    sleepAiBadge: "IA",
    hoursUnit: "h",
    subscribeTitle: "Abonnement Coach IA",
    subscribeIntro: "Abonnez-vous pour continuer avec votre coach IA personnel.",
    statusTrial: "Essai gratuit",
    statusTrialEndsOn: "se termine le {date}",
    statusTrialEnded: "Votre essai gratuit est terminé.",
    statusSubscribed: "Abonné",
    statusSubscribedUntil: "jusqu'au {date}",
    statusBlocked: "Abonnez-vous pour débloquer le coach IA.",
    choosePlan: "Choisir une formule",
    planMonthly: "Mensuel",
    planYearly: "Annuel",
    planMonthsSuffix: "mois",
    payHowTitle: "Comment payer",
    payBaridi: "BaridiMob",
    payCcp: "CCP",
    payCcpKey: "Clé",
    payNoDetails: "Les détails de paiement vous seront communiqués prochainement.",
    methodQuestion: "Comment avez-vous payé ?",
    methodBaridi: "BaridiMob",
    methodCcp: "CCP",
    proofFieldLabel: "Capture du paiement",
    proofFieldHelp: "Téléversez une capture claire de votre virement. JPG/PNG, max 5 Mo.",
    submitRequest: "Envoyer pour validation",
    submittingRequest: "Envoi…",
    requestUnderReview: "Votre paiement est en cours de vérification. Nous activerons votre abonnement bientôt.",
    requestDeclined: "Votre dernière demande a été refusée. Veuillez soumettre un nouveau paiement ci-dessous.",
    subHistoryTitle: "Historique des abonnements",
    subHistoryEmpty: "Aucun abonnement pour l'instant.",
    subStatusActive: "Actif",
    subStatusExpired: "Expiré",
    subStatusCancelled: "Annulé",
    subStartsLabel: "Début",
    subEndsLabel: "Fin",
    amountLabel: "Montant",
    currencyDa: "DA",
    backToCoach: "Retour au coach",
    manageSubscription: "Gérer l'abonnement",
    withdrawRequest: "Annuler la demande",
    cancelSubscription: "Annuler l'abonnement",
    analyzeRun: "Analyser",
    viewAnalysis: "Analyse du coach",
    askTitle: "Demandez à votre coach",
    askPlaceholder: "Comment aborder ma prochaine sortie ?",
    ask: "Demander",
    record: "Enregistrer une note vocale",
    recordStop: "Arrêter l’enregistrement",
    recording: "Enregistrement… appuyez pour arrêter.",
    transcribing: "Transcription de votre note…",
    transcribeError: "Transcription impossible. Saisissez le texte.",
    micDenied: "L’accès au microphone a été refusé.",
    thinking: "Le coach analyse votre entraînement...",
    professional: "Évaluation professionnelle recommandée",
    retry: "Réessayer",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    days: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
    dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
    stepWord: "Étape",
    ofWord: "sur",
    next: "Suivant",
    back: "Retour",
    optional: "Facultatif",
    optionalDetails: "Détails facultatifs",
    stepGoalLabel: "Objectif",
    stepBackgroundLabel: "Parcours",
    stepAvailabilityLabel: "Disponibilité",
    stepHealthLabel: "Santé",
    stepReviewLabel: "Vérifier",
    goalStepTitle: "Pour quoi vous entraînez-vous ?",
    backgroundStepTitle: "Votre parcours de coureur",
    backgroundStepText: "Cela aide le coach à définir une charge de départ sûre et réaliste.",
    availabilityStepTitle: "Quand pouvez-vous vous entraîner ?",
    healthStepTitle: "Santé et sécurité",
    healthStepText: "Indiquez ce qui doit garder votre plan sûr. Facultatif, utilisé uniquement pour personnaliser votre entraînement.",
    reviewStepTitle: "Vérifier et confirmer",
    yearsRunning: "Années de course régulière",
    peakWeeklyDistance: "Distance hebdomadaire maximale atteinte (km)",
    longestRecentRun: "Sortie récente la plus longue (km)",
    recentRaceResult: "Résultat récent de course ou test",
    recentRaceResultHint: "ex. 10 km en 52:00 le mois dernier",
    restingHeartRate: "Fréquence cardiaque au repos (bpm)",
    weight: "Poids (kg)",
    weightHint: "Sert à estimer les calories brûlées.",
    height: "Taille (cm)",
    heightHint: "Utilisée avec le poids pour le contexte morphologique.",
    sex: "Sexe",
    sexMale: "Homme",
    sexFemale: "Femme",
    birthDate: "Date de naissance",
    dobDay: "Jour",
    dobMonth: "Mois",
    dobYear: "Année",
    months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
    hoursLabel: "Heures",
    minutesLabel: "Minutes",
    secondsLabel: "Secondes",
    recordRun: "Enregistrer une sortie",
    recordHint: "Suivi GPS en direct",
    startRun: "Démarrer",
    pause: "Pause",
    resume: "Reprendre",
    finishRun: "Terminer",
    discard: "Annuler",
    statDistance: "Distance",
    statTime: "Temps",
    statMovingTime: "En mouvement",
    statPace: "Allure",
    statCurrentPace: "Allure actuelle",
    statAvgPace: "Allure moy.",
    statElevation: "Dénivelé",
    statCalories: "Calories",
    gpsAcquiring: "Acquisition du signal GPS…",
    gpsError: "Localisation impossible. Activez la permission de localisation pour ZidRun.",
    openSettings: "Ouvrir les réglages",
    runTooShort: "Sortie trop courte pour être enregistrée (au moins 100 m et 1 min).",
    savedOffline: "Enregistré sur votre téléphone — l'envoi se fera automatiquement une fois en ligne.",
    recoverTitle: "Reprendre votre sortie ?",
    recoverText: "Une sortie non terminée a été trouvée sur ce téléphone. Reprenez là où vous en étiez, ou supprimez-la.",
    recoverResume: "Reprendre",
    recoverDiscard: "Supprimer",
    statGps: "GPS",
    gpsWeak: "Faible",
    gpsFair: "Moyen",
    gpsStrong: "Bon",
    bgTitle: "Continuer l'enregistrement écran éteint",
    bgText: "Autorisez ZidRun à ignorer l'optimisation de batterie pour qu'Android ne suspende pas le GPS quand l'écran est éteint.",
    bgEnable: "Autoriser l'enregistrement en arrière-plan",
    bgEnabled: "Enregistrement en arrière-plan activé.",
    bgLocationTitle: "La localisation est désactivée",
    bgLocationText: "Autorisez l'accès à la localisation pour que ZidRun enregistre votre sortie, même écran éteint.",
    bgLocationCta: "Activer la localisation",
    statCadence: "Cadence",
    splitsLabel: "Splits (par km)",
    profileElevation: "Altitude",
    profilePace: "Allure",
    splitFastest: "Le plus rapide",
    splitSlowest: "Le plus lent",
    pendingUploads: "{n} sortie en attente d'envoi",
    retryUpload: "Réessayer l'envoi",
    shareRun: "Partager cette sortie publiquement",
    shareHint: "Les sorties publiques apparaissent dans les classements ZidRun de votre wilaya.",
    publicLabel: "Public",
    privateLabel: "Privé",
    injuryHistory: "Antécédents de blessures",
    injuryHistoryHint: "Blessures précédentes, même guéries.",
    currentInjury: "Blessures ou limitations actuelles",
    chronicConditions: "Problèmes de santé persistants",
    chronicHint: "Sélectionnez ce qui s'applique pour que le coach garde votre plan sûr.",
    healthNotes: "Médicaments ou autres notes de santé",
    consentLabel: "Je comprends que le Coach ZidRun fournit des conseils d'entraînement, pas un avis médical, et j'accepte de partager ces informations pour personnaliser mon plan.",
    consentRequired: "Veuillez confirmer pour continuer.",
    trialBadge: "Essai gratuit",
    trialEndsIn: "L'essai se termine le {date}",
    subscribedUntil: "Abonné jusqu'au {date}",
    dailyUsageLabel: "Aujourd'hui {used}/{limit}",
    subscriptionRequiredTitle: "Votre essai gratuit est terminé",
    subscriptionRequiredText: "Abonnez-vous à 500 DA/mois ou 4000 DA/an pour continuer à utiliser le coach IA. Contactez ZidRun pour activer votre abonnement.",
    requestFailed: "La requête au coach a échoué.",
    goalCreateFailed: "Impossible de créer l'objectif.",
    runSaved: "Sortie enregistrée.",
    runSaveFailed: "Impossible d'enregistrer la sortie.",
    runUpdateFailed: "Impossible de mettre à jour la sortie.",
    runSavedFeedbackFailed: "Sortie enregistrée, mais le retour du coach a échoué : {error}",
    minTrainingDays: "Choisissez au moins deux jours d'entraînement.",
    formDisclaimer: "Le Coach ZidRun fournit des conseils d'entraînement, pas un diagnostic médical.",
    highPainWarning: "Une douleur élevée suspend les conseils d'entraînement automatiques et recommande une évaluation professionnelle.",
    planSafetyNotice: "Les dates, types et plafonds de distance des séances sont appliqués par les règles de sécurité ZidRun.",
    gpsRunLabel: "Sortie GPS",
    manualRunLabel: "Sortie manuelle",
    details: "Détails",
    visibility: "Visibilité",
    runTitle: "Titre",
    runTitlePlaceholder: "ex. Sortie matinale, côtes…",
    description: "Description",
    descriptionPlaceholder: "Comment s'est passée la sortie ? À retenir…",
    deleteRun: "Supprimer",
    deleteRunTitle: "Supprimer cette sortie ?",
    deleteRunText: "La sortie et toutes ses données seront supprimées définitivement. Action irréversible.",
    deletePhotoTitle: "Supprimer cette photo ?",
    deletePhotoText: "La photo sera retirée de cette sortie.",
    confirmDelete: "Supprimer",
    cancel: "Annuler",
    photos: "Photos",
    addPhoto: "Ajouter une photo",
    photoHelp: "JPG, PNG, WebP ou GIF. Jusqu'à 6, 5 Mo max chacune.",
    photoUploading: "Envoi…",
    removePhoto: "Supprimer la photo",
    viewPhoto: "Voir la photo",
    photoUploadFailed: "Impossible d'envoyer la photo. Essayez une image plus petite.",
    saving: "Enregistrement…",
    safetyTitle: "Limite de sécurité",
    safetyText: "Le Coach ZidRun peut expliquer les tendances d'entraînement et proposer des séances prudentes. Il ne diagnostique pas les blessures et ne remplace pas un avis médical professionnel.",
    storedContext: "Contexte enregistré",
    storedItems: ["Objectif et disponibilités", "Sorties récentes et tendances globales", "Plan actuel et signaux de sécurité"],
    requiredField: "Veuillez compléter : {field}",
    invalidField: "Veuillez saisir un {field} valide.",
    challengeTitle: "Défi de la semaine",
    challengeRuns: "Sorties",
    challengeDistance: "Distance",
    streakLabel: "Semaines d'affilée",
    streakNone: "Courez cette semaine pour lancer une série.",
    streakActive: "Continuez — ne cassez pas la série !",
    tipTitle: "Conseil du coach",
    newTip: "Autre conseil",
    suggestionsTitle: "Vous ne savez pas quoi demander ? Essayez ceci",
    tips: [
      "Échauffez-vous avec 5 minutes de footing léger et des balancements de jambes avant chaque sortie pour éviter les blessures.",
      "Suivez la règle des 10 % : n'augmentez pas votre distance hebdomadaire de plus de 10 % pour éviter les blessures de surmenage.",
      "Récupérez en étirant mollets, ischio-jambiers et quadriceps après chaque sortie.",
      "Changez vos chaussures tous les 600–800 km — des semelles usées causent souvent des douleurs au genou et au tibia.",
      "Hydratez-vous avant, pendant et après les sorties longues, et portez des vêtements respirants.",
      "Les sorties faciles doivent rester conversationnelles — si vous ne pouvez pas parler, ralentissez.",
      "Privilégiez le sommeil : la plupart des progrès se font pendant la récupération, pas pendant la course."
    ],
    suggestedQuestions: [
      "Comment éviter les blessures en augmentant ma distance ?",
      "Que manger avant et après une sortie longue ?",
      "J'ai mal au genou après avoir couru — que faire ?",
      "Comment améliorer mon allure en toute sécurité ?",
      "Quelle routine d'échauffement et d'étirements adopter ?",
      "Combien de jours de repos me faut-il chaque semaine ?"
    ],
    pushPromptTitle: "Activer les rappels de course",
    pushPromptText: "Recevez une notification et un e-mail amicaux quand vous n'avez pas couru depuis un moment, pour rester régulier.",
    pushEnable: "Activer les rappels",
    pushDenied: "Les notifications sont bloquées. Activez-les dans les réglages de votre navigateur.",
    pushFailed: "Impossible d'activer les notifications. Veuillez réessayer.",
    dismiss: "Ignorer"
  },
  ar: {
    eyebrow: "مدرب ZidRun",
    title: "تدرّب بخطوة تالية واضحة",
    intro: "حدد هدفك، سجل كل حصة، واحصل على خطة حذرة مبنية على تدريبك الأخير.",
    overview: "نظرة عامة",
    plan: "الخطة",
    runs: "الحصص",
    coach: "المدرب",
    setupTitle: "أنشئ هدف الجري",
    setupText: "أيام توفرّك وحجم تدريبك الأخير يحددان حدود الخطة الآمنة.",
    saveGoal: "إنشاء الهدف",
    editGoal: "تعديل الهدف",
    editGoalTitle: "تعديل هدفك",
    editGoalText: "غيّر أي تفصيل أدناه. سيستخدم خطتك القادمة الإجابات الجديدة.",
    saveChanges: "حفظ التغييرات",
    goalType: "الهدف",
    targetDate: "تاريخ الهدف",
    targetDateFuture: "يجب أن يكون التاريخ المستهدف في المستقبل.",
    customGoalRequired: "يرجى وصف هدفك المخصّص.",
    trainingDaysInvalid: "اختر بين 2 و7 أيام تدريب.",
    longRunDayInvalid: "يجب أن يكون يوم الجري الطويل أحد أيام تدريبك.",
    fieldInvalid: "يرجى التحقق من الحقل المحدد والمحاولة مرة أخرى.",
    targetDistance: "المسافة المستهدفة (كم)",
    targetTime: "الوقت المستهدف (HH:MM:SS)",
    experience: "الخبرة",
    weeklyDistance: "المسافة الأسبوعية الحالية (كم)",
    trainingDays: "أيام التدريب المتاحة",
    longRunDay: "يوم الحصة الطويلة",
    constraints: "قيود التدريب",
    injuryNotes: "الإصابات أو الملاحظات الصحية",
    responseLanguage: "لغة المدرب",
    currentGoal: "الهدف الحالي",
    target: "الموعد",
    thisWeek: "هذا الأسبوع",
    last28: "آخر 28 يوما",
    avgPace: "متوسط الوتيرة",
    fatigue: "أعلى تعب",
    nextWorkout: "الحصة القادمة",
    noWorkout: "أنشئ خطة أسبوعية لعرض الحصة القادمة.",
    recentCoach: "آخر مراجعة للمدرب",
    noReview: "لا توجد مراجعة بعد.",
    generatePlan: "إنشاء خطة أسبوعية",
    reviewPlan: "تحضير الأسبوع القادم",
    generating: "المدرب يحضر خطتك...",
    acceptPlan: "اعتماد الخطة",
    activePlan: "الخطة النشطة",
    today: "اليوم",
    planEndedTitle: "لم يتم تخطيط هذا الأسبوع بعد",
    planEndedText: "انتهى أسبوع خطتك النشطة. أنشئ خطة هذا الأسبوع للحصول على حصة اليوم وتذكيراتك اليومية.",
    workoutDone: "تم",
    workoutMissed: "فائتة",
    draftPlan: "الخطة المقترحة",
    logRun: "تسجيل حصة",
    durationMinutes: "المدة (دقيقة)",
    distance: "المسافة (كم)",
    startedAt: "التاريخ والوقت",
    effort: "المجهود",
    runFatigue: "التعب",
    pain: "الألم",
    elevation: "الارتفاع المكتسب (م)",
    heartRate: "متوسط نبض القلب",
    symptoms: "الأعراض",
    notes: "ملاحظات الحصة",
    analyzeNow: "الحصول على رأي المدرب بعد الحفظ",
    saveRun: "حفظ الحصة",
    savingRun: "جار الحفظ...",
    runHistory: "الحصص الأخيرة",
    noRuns: "لم تسجل أي حصة بعد.",
    sleep: "النوم",
    sleepHeading: "سجل النوم",
    sleepIntro: "تابع لياليك — النوم الجيد هو حين يتحول التدريب إلى لياقة.",
    logSleep: "تسجيل نوم",
    sleepModeHours: "ساعات",
    sleepModeTimes: "الأوقات",
    sleepModeText: "وصف",
    sleepHoursLabel: "ساعات النوم",
    sleepBedTime: "وقت النوم",
    sleepWakeTime: "وقت الاستيقاظ",
    sleepTextLabel: "صف نومك (بأي لغة)",
    sleepTextPlaceholder: "مثال: نمت حوالي 7 ساعات، أو من 11 ليلاً إلى 6 صباحاً",
    sleepNight: "الليلة",
    sleepNoteLabel: "ملاحظة (اختياري)",
    saveSleep: "حفظ",
    savingSleep: "جارٍ الحفظ…",
    sleepSaved: "تم حفظ النوم.",
    sleepSaveFailed: "تعذر حفظ النوم.",
    noSleep: "لم تسجل أي نوم بعد.",
    sleepAvgLabel: "متوسط 7 ليالٍ",
    sleepAiBadge: "ذكاء",
    hoursUnit: "س",
    subscribeTitle: "اشتراك المدرب الذكي",
    subscribeIntro: "اشترك لمواصلة التدريب مع مدربك الذكي الشخصي.",
    statusTrial: "فترة تجريبية مجانية",
    statusTrialEndsOn: "تنتهي في {date}",
    statusTrialEnded: "انتهت فترتك التجريبية المجانية.",
    statusSubscribed: "مشترك",
    statusSubscribedUntil: "حتى {date}",
    statusBlocked: "اشترك لفتح المدرب الذكي.",
    choosePlan: "اختر باقة",
    planMonthly: "شهري",
    planYearly: "سنوي",
    planMonthsSuffix: "شهر",
    payHowTitle: "طريقة الدفع",
    payBaridi: "بريدي موب",
    payCcp: "الحساب الجاري البريدي",
    payCcpKey: "المفتاح",
    payNoDetails: "سيتم إرسال تفاصيل الدفع إليك قريباً.",
    methodQuestion: "كيف دفعت؟",
    methodBaridi: "بريدي موب",
    methodCcp: "الحساب الجاري البريدي",
    proofFieldLabel: "لقطة شاشة للدفع",
    proofFieldHelp: "ارفع لقطة شاشة واضحة للتحويل. JPG/PNG، بحد أقصى 5 ميغابايت.",
    submitRequest: "إرسال للمراجعة",
    submittingRequest: "جارٍ الإرسال…",
    requestUnderReview: "دفعتك قيد المراجعة. سنقوم بتفعيل اشتراكك قريباً.",
    requestDeclined: "تم رفض طلبك الأخير. يرجى إرسال دفعة جديدة أدناه.",
    subHistoryTitle: "سجل الاشتراكات",
    subHistoryEmpty: "لا توجد اشتراكات بعد.",
    subStatusActive: "نشط",
    subStatusExpired: "منتهٍ",
    subStatusCancelled: "ملغى",
    subStartsLabel: "البداية",
    subEndsLabel: "النهاية",
    amountLabel: "المبلغ",
    currencyDa: "دج",
    backToCoach: "العودة إلى المدرب",
    manageSubscription: "إدارة الاشتراك",
    withdrawRequest: "إلغاء الطلب",
    cancelSubscription: "إلغاء الاشتراك",
    analyzeRun: "تحليل الحصة",
    viewAnalysis: "تحليل المدرب",
    askTitle: "اسأل مدربك",
    askPlaceholder: "كيف أتعامل مع حصتي القادمة؟",
    ask: "اسأل المدرب",
    record: "سجّل ملاحظة صوتية",
    recordStop: "إيقاف التسجيل",
    recording: "جارٍ التسجيل… اضغط للإيقاف.",
    transcribing: "جارٍ نسخ ملاحظتك…",
    transcribeError: "تعذّر النسخ. الرجاء الكتابة بدلاً من ذلك.",
    micDenied: "تم رفض الوصول إلى الميكروفون.",
    thinking: "المدرب يراجع تدريبك...",
    professional: "يوصى باستشارة مختص",
    retry: "إعادة المحاولة",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    days: ["أحد", "إثن", "ثلا", "أرب", "خمي", "جمع", "سبت"],
    dayNames: ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    stepWord: "خطوة",
    ofWord: "من",
    next: "التالي",
    back: "رجوع",
    optional: "اختياري",
    optionalDetails: "تفاصيل اختيارية",
    stepGoalLabel: "الهدف",
    stepBackgroundLabel: "الخلفية",
    stepAvailabilityLabel: "التوفر",
    stepHealthLabel: "الصحة",
    stepReviewLabel: "مراجعة",
    goalStepTitle: "لماذا تتدرّب؟",
    backgroundStepTitle: "خلفيتك في الجري",
    backgroundStepText: "يساعد هذا المدرب على تحديد حِمل بداية آمن وواقعي.",
    availabilityStepTitle: "متى يمكنك التدريب؟",
    healthStepTitle: "الصحة والسلامة",
    healthStepText: "شارك ما يلزم لإبقاء خطتك آمنة. هذا اختياري ويُستخدم فقط لتخصيص تدريبك.",
    reviewStepTitle: "مراجعة وتأكيد",
    yearsRunning: "سنوات الجري المنتظم",
    peakWeeklyDistance: "أعلى مسافة أسبوعية وصلت إليها (كم)",
    longestRecentRun: "أطول حصة حديثة (كم)",
    recentRaceResult: "نتيجة سباق أو اختبار حديث",
    recentRaceResultHint: "مثال: 10 كم في 52:00 الشهر الماضي",
    restingHeartRate: "نبض القلب أثناء الراحة (نبضة/د)",
    weight: "وزن الجسم (كغ)",
    weightHint: "يُستخدم لتقدير السعرات الحرارية المحروقة.",
    height: "الطول (سم)",
    heightHint: "يُستخدم مع الوزن لفهم بنية الجسم.",
    sex: "الجنس",
    sexMale: "ذكر",
    sexFemale: "أنثى",
    birthDate: "تاريخ الميلاد",
    dobDay: "اليوم",
    dobMonth: "الشهر",
    dobYear: "السنة",
    months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
    hoursLabel: "ساعات",
    minutesLabel: "دقائق",
    secondsLabel: "ثوانٍ",
    recordRun: "تسجيل جري",
    recordHint: "تتبّع GPS مباشر",
    startRun: "ابدأ",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    finishRun: "إنهاء",
    discard: "إلغاء",
    statDistance: "المسافة",
    statTime: "الوقت",
    statMovingTime: "زمن الحركة",
    statPace: "الوتيرة",
    statCurrentPace: "الوتيرة الحالية",
    statAvgPace: "متوسط الوتيرة",
    statElevation: "الارتفاع",
    statCalories: "سعرات",
    gpsAcquiring: "جارٍ التقاط إشارة GPS…",
    gpsError: "تعذّر تحديد موقعك. فعّل إذن الموقع لتطبيق ZidRun.",
    openSettings: "فتح الإعدادات",
    runTooShort: "الجري قصير جدًا للحفظ (يلزم 100 م ودقيقة على الأقل).",
    savedOffline: "تم الحفظ على هاتفك — سيُرفع تلقائيًا عند عودة الاتصال.",
    recoverTitle: "استئناف الجري؟",
    recoverText: "وجدنا جريًا غير مكتمل على هذا الهاتف. تابع من حيث توقفت، أو احذفه.",
    recoverResume: "استئناف",
    recoverDiscard: "حذف",
    statGps: "GPS",
    gpsWeak: "ضعيف",
    gpsFair: "متوسط",
    gpsStrong: "قوي",
    bgTitle: "متابعة التسجيل والشاشة مطفأة",
    bgText: "اسمح لـ ZidRun بتجاهل تحسين البطارية حتى لا يوقف أندرويد GPS عندما تكون الشاشة مطفأة.",
    bgEnable: "السماح بالتسجيل في الخلفية",
    bgEnabled: "تسجيل الخلفية مُفعّل.",
    bgLocationTitle: "الموقع غير مُفعّل",
    bgLocationText: "اسمح بالوصول إلى الموقع حتى يتمكّن ZidRun من تسجيل جريك، حتى عند إطفاء الشاشة.",
    bgLocationCta: "تفعيل الموقع",
    statCadence: "الإيقاع",
    splitsLabel: "المقاطع (لكل كم)",
    profileElevation: "الارتفاع",
    profilePace: "الوتيرة",
    splitFastest: "الأسرع",
    splitSlowest: "الأبطأ",
    pendingUploads: "{n} جري بانتظار الرفع",
    retryUpload: "إعادة محاولة الرفع",
    shareRun: "مشاركة هذا الجري علنًا",
    shareHint: "تظهر الجريات العلنية في تصنيفات ZidRun الخاصة بولايتك.",
    publicLabel: "عام",
    privateLabel: "خاص",
    injuryHistory: "تاريخ الإصابات السابقة",
    injuryHistoryHint: "إصابات سابقة حتى وإن تعافيت منها.",
    currentInjury: "إصابات أو قيود حالية",
    chronicConditions: "حالات صحية مزمنة",
    chronicHint: "اختر ما ينطبق ليحافظ المدرب على خطتك آمنة.",
    healthNotes: "أدوية أو ملاحظات صحية أخرى",
    consentLabel: "أفهم أن مدرب ZidRun يقدّم إرشادات تدريبية وليست نصيحة طبية، وأوافق على مشاركة هذه المعلومات لتخصيص خطتي.",
    consentRequired: "يرجى التأكيد للمتابعة.",
    trialBadge: "تجربة مجانية",
    trialEndsIn: "تنتهي التجربة في {date}",
    subscribedUntil: "مشترك حتى {date}",
    dailyUsageLabel: "اليوم {used}/{limit}",
    subscriptionRequiredTitle: "انتهت تجربتك المجانية",
    subscriptionRequiredText: "اشترك مقابل 500 دج شهريًا أو 4000 دج سنويًا لمواصلة استخدام مدرب الذكاء الاصطناعي. تواصل مع ZidRun لتفعيل اشتراكك.",
    requestFailed: "فشل طلب المدرب.",
    goalCreateFailed: "تعذّر إنشاء الهدف.",
    runSaved: "تم حفظ الحصة.",
    runSaveFailed: "تعذّر حفظ الحصة.",
    runUpdateFailed: "تعذّر تحديث الحصة.",
    runSavedFeedbackFailed: "تم حفظ الحصة، لكن تعذّر الحصول على رأي المدرب: {error}",
    minTrainingDays: "اختر يومين تدريب على الأقل.",
    formDisclaimer: "يقدّم مدرب ZidRun إرشادات تدريبية وليس تشخيصًا طبيًا.",
    highPainWarning: "الألم الشديد يوقف النصائح التدريبية التلقائية ويوصي بتقييم مختص.",
    planSafetyNotice: "تواريخ الحصص وأنواعها وحدود المسافة تُطبَّق وفق قواعد سلامة ZidRun.",
    gpsRunLabel: "حصة GPS",
    manualRunLabel: "حصة يدوية",
    details: "التفاصيل",
    visibility: "الظهور",
    runTitle: "العنوان",
    runTitlePlaceholder: "مثال: جري صباحي، تكرارات صعود…",
    description: "الوصف",
    descriptionPlaceholder: "كيف كانت الحصة؟ أي شيء يستحق التذكّر…",
    deleteRun: "حذف الحصة",
    deleteRunTitle: "حذف هذه الحصة؟",
    deleteRunText: "سيؤدي هذا إلى حذف الحصة وكل بياناتها نهائيًا. لا يمكن التراجع.",
    deletePhotoTitle: "إزالة هذه الصورة؟",
    deletePhotoText: "ستتم إزالة الصورة من هذه الحصة.",
    confirmDelete: "حذف",
    cancel: "إلغاء",
    photos: "الصور",
    addPhoto: "إضافة صورة",
    photoHelp: "JPG أو PNG أو WebP أو GIF. حتى 6 صور، 5 ميغابايت لكل صورة.",
    photoUploading: "جارٍ الرفع…",
    removePhoto: "حذف الصورة",
    viewPhoto: "عرض الصورة",
    photoUploadFailed: "تعذّر رفع الصورة. جرّب صورة أصغر.",
    saving: "جارٍ الحفظ…",
    safetyTitle: "حدود السلامة",
    safetyText: "يمكن لمدرب ZidRun شرح أنماط التدريب واقتراح حصص حذرة. لا يشخّص الإصابات ولا يحل محل الرعاية الطبية المختصة.",
    storedContext: "السياق المخزّن",
    storedItems: ["الهدف والتوفر", "الحصص الأخيرة والاتجاهات العامة", "الخطة الحالية وإشارات السلامة"],
    requiredField: "يرجى إكمال: {field}",
    invalidField: "يرجى إدخال {field} صحيح.",
    challengeTitle: "تحدي هذا الأسبوع",
    challengeRuns: "الحصص",
    challengeDistance: "المسافة",
    streakLabel: "أسابيع متتالية",
    streakNone: "اجرِ هذا الأسبوع لتبدأ سلسلة.",
    streakActive: "واصل — لا تكسر السلسلة!",
    tipTitle: "نصيحة المدرب",
    newTip: "نصيحة أخرى",
    suggestionsTitle: "لا تعرف ماذا تسأل؟ جرّب أحد هذه",
    tips: [
      "ابدأ بإحماء 5 دقائق من الجري الخفيف وتمارين تأرجح الساق قبل كل حصة لتفادي الإصابات.",
      "اتبع قاعدة الـ10٪: لا تزد مسافتك الأسبوعية بأكثر من 10٪ لتجنب إصابات الإجهاد.",
      "قم بالتهدئة وإطالة عضلات الساق والفخذ بعد كل حصة لتسريع الاستشفاء.",
      "غيّر حذاء الجري كل 600–800 كم — النعل المهترئ سبب شائع لآلام الركبة والساق.",
      "اشرب الماء قبل الجري الطويل وأثناءه وبعده، والبس ملابس مريحة تسمح بالتهوية.",
      "يجب أن تكون الحصص السهلة بوتيرة تسمح بالحديث — إن لم تستطع الكلام فأبطئ.",
      "أعطِ النوم أولوية: معظم تحسّن لياقتك يحدث أثناء الاستشفاء وليس أثناء الجري."
    ],
    suggestedQuestions: [
      "كيف أتجنب الإصابات مع زيادة المسافة؟",
      "ماذا آكل قبل الجري الطويل وبعده؟",
      "تؤلمني ركبتي بعد الجري — ماذا أفعل؟",
      "كيف أحسّن وتيرتي بأمان؟",
      "ما روتين الإحماء والإطالة الجيد؟",
      "كم يوم راحة أحتاج كل أسبوع؟"
    ],
    pushPromptTitle: "تفعيل تذكيرات الجري",
    pushPromptText: "احصل على تنبيه وبريد ودّي عندما تنقطع عن الجري فترة، لتبقى منتظمًا.",
    pushEnable: "تفعيل التذكيرات",
    pushDenied: "الإشعارات محظورة. فعّلها من إعدادات المتصفح.",
    pushFailed: "تعذّر تفعيل الإشعارات. حاول مرة أخرى.",
    dismiss: "تجاهل"
  }
} as const;

export function getCoachCopy(locale: CoachLocale) {
  return copy[locale];
}

export type CoachCopy = ReturnType<typeof getCoachCopy>;

export const goalOptions = [
  ["GENERAL_FITNESS", "General fitness", "Forme générale", "لياقة عامة"],
  ["FIVE_K", "5K", "5 km", "5 كم"],
  ["TEN_K", "10K", "10 km", "10 كم"],
  ["HALF_MARATHON", "Half marathon", "Semi-marathon", "نصف ماراثون"],
  ["MARATHON", "Marathon", "Marathon", "ماراثون"],
  ["TRAIL", "Trail", "Trail", "جري جبلي"],
  ["OTHER", "Other", "Autre", "آخر"]
] as const;

export function localizedOption(option: readonly [string, string, string, string], locale: CoachLocale) {
  return option[locale === "en" ? 1 : locale === "fr" ? 2 : 3];
}

export const chronicConditionOptions = [
  ["NONE", "None", "Aucun", "لا شيء"],
  ["ASTHMA", "Asthma", "Asthme", "الربو"],
  ["DIABETES", "Diabetes", "Diabète", "السكري"],
  ["HYPERTENSION", "High blood pressure", "Hypertension", "ارتفاع ضغط الدم"],
  ["HEART_CONDITION", "Heart condition", "Problème cardiaque", "حالة قلبية"],
  ["THYROID", "Thyroid condition", "Trouble thyroïdien", "اضطراب الغدة الدرقية"],
  ["ANEMIA", "Anemia", "Anémie", "فقر الدم"],
  ["OTHER", "Other", "Autre", "أخرى"]
] as const;

